export default {
  "gpmsTest": "Community",
  "adminMenu": "ADMIN",

  // columns
  "colDate": "DATE",
  "colNumber": "No",
  "colName": "Name",
  "colConnReqCount": "ReqCnt",
  "colConnSuccess": "ConnSuccCnt",
  "colConnFail": "ConnFailCnt",
  "colConnRequest": "ConnReqCnt",

  "colBootViolated": "BootViolated",
  "colExeViolated": "ExeViolated",
  "colOSViolated": "OSViolated",
  "colMediaViolated": "MediaViolated",

  "colRegCount": "RegCnt",
  "colRevokeCount": "RevokeCnt",

  "colClientId": " ClientId",
  "colClientName": "ClientName",
  "colClientGroup": "ClientGroup",
  "colGroupName": "GroupName",
  "colClientCount": "ClientCnt",
  "colUser": "User",
  "colUserId": "UserId",
  "colLogType": "LogType",
  "colLogInfo": "LogInfo",
  "colRegDate": "RegDate",
  "colModDate": "ModDate",
  "colStatus": "Status",
  "colEdit": "Edit",
  "colEditDelete": "Edit/Del",

  "colId": "ID",
  "colLastLoginDate": "LastLoginDate",
  "colLastLoginIp": "LastLoginIp",
  "colLoginId": "LoginId",
  "colUseRate": "UseRate",

  "colClientRegKey": "ClientRegKey",
  "colKeyValidDate": "ValidDate",
  "colCertExpireDate": "ExpireDate",

  "colRefClientId": "RefClient",
  "colProfile": "Profile",
  "colPackageInfo": "PackageInfo",
  "colPackageName": "PackageName",

  "colArchitecture": "Architecture",
  "colInstalledVersion": "InstalledVer.",
  "colVersion": "Version",
  "colAvailVersion": "AvailableVer.",

  "colJobNo": "JobNo",
  "colJobName": "JobName",
  "colJobStatus": "Status",
  "colJobProgressStatus": "Status",
  "colTargetCnt": "TargetCnt",
  "colJobErrorCnt": "ErrorCnt",
  "colJobCompCnt": "CompCnt",
  "colRegUser": "RegUser",
  "colModUser": "ModUser",

  "colDivision": "Division",
  "colRuleName": "RuleName",
  "colRuleId": "RuleId",

  // options
  "optDate": "Date",
  "searchStartDate": "From-Date",
  "searchEndDate": "To-Date",
  "optDivision": "Division",
  "optViolatedDivision": "ViolatedDiv",

  "optClientStatus": "ClientStatus",
  "optKeyword": "Keyword",

  // Buttons
  "btnSearch": "Search",
  "btnRegist": "Regist",
  "btnSave": "Save",
  "btnClose": "Close",
  "btnCreate": "Create",
  "btnAdd": "Add",

  // Menus
  "menuDashboard": "Dashboard",
  "menuStatistic": "Statistic",
  "menuDailyViolated": "DailyViolatedStatics",
  "menuDailyConnected": "DailyConnectedStatics",
  "menuDailyRegistered": "DailyRegisteredStatics",
  "menuSecurityLog": "SecurityLog",

  "menuClient": "Client",
  "menuClientManage": "ClientMng",
  "menuClientRegKey": "RegKeyMng",
  "menuClientRule": "ClientRule",
  "menuClientSetup": "ClientSetup",
  "menuClientHosts": "HOSTS",
  "menuClientUpdateServer": "UpdateServer",

  "menuSoftware": "Software",
  "menuPackageManage": "PackageMng",
  "menuProfileManage": "ProfileMng",

  "menuUser": "User",
  "menuUserManage": "UserMng",

  "menuUseRule": "ClientUseRule",
  "menuMediaRuleManage": "MediaRule",
  "menuBrowserRuleManage": "BrowserRule",
  "menuSecurityRuleManage": "SecurityRule",
  "menuSoftwareRuleManage": "SoftwareRule",
  
  "menuDesktop": "Desktop",
  "menuDesktopManage": "DesktopMng",
  "menuDesktopAppManage": "DesktopAppMng",
  "menuCloudServiceManage": "CloudServiceMng",
  "menuThemeManage": "ThemeMng",

  "menuJob": "Job",
  "menuJobManage": "JobMng",

  // 공통
  "selOffline": "Offline",
  "selOnline": "Online",
  "selViolated": "Violated",
  "selUnviolated": "Unviolated",
  "lbDesc": "Desc.",
  "lbName": "Name",
  "lbClientId": "ClientId",
  "dtSystemError": "System Error",
  "dtSystemNotice": "System Notice",
  "selBasic": "Basic",
  "selOrdinary": "Ordinary",
  "msgInputName": "Please enter your name."
  "selDelete": "Delete",
  "selNoDelete": "NoDelete",
  "msgCopyRule": "Would you like to copy this rule and create a new one?",
  "dtCopy": "Copy",
  "dtApply": "Apply",
  "msgApplyRuleToChild": "Do you want to apply this rule to suborganizations?",
  "dtNameAndId": "Name(ID)",
  "selNoSelected": "NoSelect",
  "msgShowSpecAsSelectRule": "When you select the rule information, details are displayed.",


  // 일별접속통계
  "connectRequestCount": "ConnReqCnt",
  "connReqUserCount": "ConnReq UserCnt",
  "connReqClientCount": "ConnReq ClientCnt",
  "connSuccessCount": "ConnSuccCnt",
  "connFailCount": "ConnFailCnt",

  // 단말등록통계
  "regClientCount": "RegClientCnt",
  "revokeClientCount": "RevokeClientCnt",

  // 단말관리
  "ttAddNewGroup": "Create New Group",
  "ttDeleteGroup": "Delete Group",
  "ttAddClientInGroup": "Add Client To Group",
  "ttDeleteClientFromGroup": "Delete Client From Group",
  "ttRevokeClient": "Revoke Client",

  "spClientGroup": "Client Group",
  "spClientDesc": "Client Desc.",
  "spClientGroupName": "Group Name",
  "spClientGroupDesc": "Group Desc",
  "spIsOnline": "Is Online",
  "spHomeSizeRate": "Home Use Rate",
  "spInstalledPkgCnt": "Installed Package Cnt",
  "spBootViolated": "Boot Violated",
  "spExeViolated": "Exe Violated",
  "spMediaViolated": "Media Violated",
  "spOSViolated": "OS Violated",
  "spClientRegDate": "Client Reg Date",
  "msgRevokedClient": "this is revoked client.",

  "dtDeleteClient": "Client Delete",
  "msgDeleteClient": "단말({{clientCnt}}개)을 삭제하시겠습니까?",

  "dtAddGroup": "Client Group Register",
  "dtEditGroup": "Client Group Edit",
  "dtDeleteGroup": "Client Group Delete",
  "msgDeleteGroup": "단말그룹({{groupCnt}}개)을 삭제하시겠습니까?",
  "dtViewGroup": "Client Group Information",
  "dtAddClientInGroup": "Add Client To Group",
  "msgAddClientInGroup": "선택한 단말({{clientCnt}}개)을 단말그룹('{{groupName}}')으로 변경하시겠습니까?"
  "dtDeleteClientFromGroup": "Delete Client From Group",

  "msgAddGroup": "Do you want to register the client group?",
  "msgEditGroup": "Do you want to edit the client group?",
  "msgDeleteGroup": "Do you want to delete the client group?",
  "msgInputGroupName": "Please enter a client group name.",
  "msgSelectClient": "Please select a client.",
  "msgCfmDeleteClientFromGroup": "Are you sure you want to delete the selected client from the group?",
  "msgCfmSelectGroupForInsertClient": "Select the group to which you want to add the client.",

  // 단말 등록키 관리
  "dtAddClientKey": "단말 등록키 등록",
  "msgAddClientKey": "단말등록키를 등록하시겠습니까?",
  "dtEditClientKey": "단말 등록키 수정",
  "msgEditClientKey": "단말등록키를 수정하시겠습니까?",
  "dtDeleteClientKey": "단말 등록키 삭제",
  "msgDeleteClientKey": "단말등록키 ('{{regKeyNo}}')을 삭제하시겠습니까?",
  "dtViewClientKey": "단말 등록키 정보",
  "msgCopyedIntoClipboard": "단말등록키가 클립보드에 복사되었습니다. 붙여넣기 하실 수 있습니다.",
  "spClientRegKey": "등록키",
  "msgCreateClientRegKey": "단말 등록키를 생성하세요.",
  "btnCreateClientRegKey": "키생성",
  "btnCopyToClipboard": "복사하기",
  "colKeyValidDate": "유효날짜",
  "colCertExpireDate": "인증서만료날짜",
  "lbKeyValidDate": "유효날짜",
  "lbCertExpireDate": "인증서만료날짜",
  "lbValidRegIp": "유효 IP 범위",
  "msgInputValidIp": "유효 아이피를 입력하세요.",
  "msgHelpInputIp": "여러개인 경우 콤마(.) 로 구분, 또는 "-" 로 영역 설정 가능합니다.",
  "msgSampleIputIp": "(샘플) '127.0.0.1, 169.0.0.1' 또는 '127.0.0.1 - 127.0.0.10'",

  // 프로파일정보
  "dtExecuteClientProfile": "단말프로파일 실행",
  "msgExecuteClientProfile": "단말프로파일을 실행하시겠습니까?",
  "dtAddClientProfile": "단말프로파일 등록",
  "msgAddClientProfile": "단말프로파일을 등록하시겠습니까?",
  "dtEditClientProfile": "단말프로파일 수정",
  "msgEditClientProfile": "단말프로파일을 수정하시겠습니까?",
  "dtDeleteClientProfile": "단말프로파일 삭제",
  "msgDeleteClientProfile": "단말프로파일 ('{{profileNo}}')를 삭제하시겠습니까?",
  "dtViewClientProfile": "단말프로파일 정보",
  "lbProfileName": "프로파일 이름",
  "msgInputProfileName": "프로파일 이름을 입력하세요.",
  "lbProfileDesc": "프로파일 설명",
  "lbProfileEtcHandle": "기타 패키지 처리방식",
  "lbReferenceClient": "레퍼런스 단말",
  "msgSelectRefClient": "레퍼런스 단말을 선택하세요.",
  "msgSelectClientInBelow": "아래 목록에서 단말을 선택하세요.",
  "lbTargetClient": "대상 단말",
  "lbPackageInfo": "패키지 정보",
  
  // 패키지관리
  "selShowDiffPackage": "차이있는 패키지만 보기",
  "selShowAllPackage": "전체 패키지 보기",
  "ttPackageUpdate": "패키지 업데이트",
  "ttPackageDelete": "패키지 삭제",
  "dtPackageUpdate": "패키지 업데이트",
  "msgPackageUpdate": "패키지({{packageCnt}}개)를 업데이트하시겠습니까?",
  "dtPackageDelete": "패키지 삭제",
  "msgPackageDelete": "패키지({{packageCnt}}개)를 삭제하시겠습니까?",
  "msgCreatePkgUpdateJob": "패키지 업데이트 작업이 생성되었습니다.",
  "msgNoCreatePkgUpdateJob": "패키지 업데이트 작업이 생성되지 못하였습니다.",
  "msgCreatePkgDeleteJob": "패키지 삭제 작업이 생성되었습니다.",
  "msgNoCreatePkgDeleteJob": "패키지 삭제 작업이 생성되지 못하였습니다.",
  "btnAllUpdate": "전체업데이트",
  "btnAddPackage": "패키지추가",
  "dtInstallSelectedPackage": "선택한 패키지 설치",
  "msgInstallSelectedPackage": "선택한 패키지를 설치하시겠습니까?",
  "dtAllPackageUpadte": "전체패키지 업데이트",
  "msgAllPackageUpadte": "선택하신 단말 또는 그룹에 업데이트 가능 패키지를 모두 업데이트 하겠습니까?",
  "msgSelectClientForUpdate": "패키지를 설치할 단말을 선택하세요.",
  "dtAddClientPackage": "단말패키지 등록",
  "msgAddClientPackage": "단말패키지를 등록하시겠습니까?",
  "dtEditClientPackage": "단말패키지 수정",
  "msgEditClientPackage": "단말패키지를 수정하시겠습니까?",
  "dtViewClientPackage": "단말패키지 정보",
  "lbPackageName": "단말패키지 이름",
  "lbPackageDesc": "단말패키지 설명",

  // 작업관리
  "dtJobStatus": "작업상태",
  "msgNoResult": "결과가 없습니다.",
  "dtJobModule": "모듈",
  "dtJobTask": "타스크",
  "dtJobMessage": "메세지",
  "dtJobInfo": "작업정보",
  "dtJobNo": "작업번호",
  "dtJobName": "작업이름",
  "dtJobRegDate": "작업생성일",
  "dtJobTargetResult": "작업대상 결과정보",
  "dtJobResultStatus": "작업상태(결과)",
  "dtJobModuleInfo": "작업모듈 정보",
  "btnCancelJob": "작업취소",
  "dtCancelJob": "작업 취소",
  "msgCancelJob": "작업대상 단말중 '작업전' 상태 단말의 작업을 취소하시겠습니까?",

  // 단말정책설정
  "dtAddClientConf": "단말정책설정 등록",
  "msgAddClientConf": "단말정책설정를 등록하시겠습니까?",
  "dtEditClientConf": "단말정책설정 수정",
  "msgEditClientConf": "단말정책설정를 수정하시겠습니까?",
  "dtCopyClientConf": "단말정책설정 복사",
  "msgCopyClientConf": "단말정책설정를 복사하였습니다.",
  "dtViewClientConf": "단말정책설정 정보",
  "dtOSProtect": "운영체제보호",
  "dtInitHomeFolder": "홈폴더 초기화",
  "dtTrustedBoot": "신뢰부팅",
  "dtExeProtect": "실행파일보호",
  "dtMediaProtect": "매체제어",
  "dtAgent": "에이전트",
  "selStop": "중단",
  "selRun": "구동",
  "selExecute": "실행",
  "lbViolatedLogLebel": "침해 로그레벨(수준)",
  "lbClientLogLevel": "단말 로그보기에 표시되는 로그레벨(수준)",
  "lbServerLogLevel": "서버로 전송하는 로그레벨(수준)",
  "lbDeleteAfterSend": "전송후 삭제여부",
  "lbSaveDateAfterSend": "서버전송후 로그보관일수",
  "msgHelpNoDeleteIfZero": "'0' 으로 설정시 삭제하지 않음",
  "dtClientLogSetup": "단말 로그 (JournalD Log) 설정",
  "lbLogFileMax": "로그파일 최대크기(MB)",
  "msgCreateNewFileIfMax": "최대크기에 도달하면 새로운 파일을 생성",
  "msgMegabateUnit": "단위는 Mega-Byte",
  "lbSavedLogFileCount": "보관할 로그파일 갯수",
  "msgDeleteFileIfOverCount": "갯수가 초과되면 오래된 파일을 삭제",
  "lbMinimumDiskSizeRate": "최소 확보 디스크 공간(%)",
  "msgHelpMinimumDiskSizeRate": "단위는 '%'이며 디폴트는 '10%'",
  "msgHelpDiskSizeData": "저널디의 'SystemKeepFree' 설정값",
  "dtSetupConnectableIp": "접속 가능 아이피 설정",
  "dtPermitAllIp": "전체 아이피 허용",
  "selPermit": "허용함",
  "selNoPermit": "허용안함",
  "dtSetupLogLevel": "로그레벨 설정",
  "dtIsUseDeleteFunc": "삭제기능 사용여부",
  "lbSetupClient": "단말 설정",


};
