export default {
  "gpmsTest": "Community",
  "adminMenu": "ADMIN",

  // columns
  "colDate": "DATE",
  "colNumber": "No",
  "colName": "Name",
  "colConnReqCount": "ReqCnt",
  "colConnSuccess": "ConnSuccCnt",
  "colConnFail": "ConnFailCnt",
  "colConnRequest": "ConnReqCnt",

  "colBootViolated": "BootViolated",
  "colExeViolated": "ExeViolated",
  "colOSViolated": "OSViolated",
  "colMediaViolated": "MediaViolated",

  "colRegCount": "RegCnt",
  "colRevokeCount": "RevokeCnt",

  "colClientId": " ClientId",
  "colClientName": "ClientName",
  "colClientGroup": "ClientGroup",
  "colGroupName": "GroupName",
  "colClientCount": "ClientCnt",
  "colUser": "User",
  "colUserId": "UserId",
  "colUserNm": "UserName",
  "colLogType": "LogType",
  "colLogInfo": "LogInfo",
  "colRegDate": "RegDate",
  "colModDate": "ModDate",
  "colStatus": "Status",
  "colEdit": "Edit",
  "colEditDelete": "Edit/Del",

  "colId": "ID",
  "colLastLoginDate": "LastLoginDate",
  "colLastLoginIp": "LastLoginIp",
  "colLoginId": "LoginId",
  "colUseRate": "UseRate",

  "colClientRegKey": "ClientRegKey",
  "colKeyValidDate": "ValidDate",
  "colCertExpireDate": "ExpireDate",

  "colRefClientId": "RefClient",
  "colProfile": "Profile",
  "colPackageInfo": "PackageInfo",
  "colPackageName": "PackageName",

  "colArchitecture": "Architecture",
  "colInstalledVersion": "InstalledVer.",
  "colVersion": "Version",
  "colAvailVersion": "AvailableVer.",

  "colJobNo": "JobNo",
  "colJobName": "JobName",
  "colJobHistory": "JobHistory",
  "colJobStatus": "Status",
  "colReqJob": "ReqJob",
  "colJobType": "JobType",
  "colJobProgressStatus": "Status",
  "colTargetCnt": "TargetCnt",
  "colJobErrorCnt": "ErrorCnt",
  "colJobCompCnt": "CompCnt",
  "colRegUser": "RegUser",
  "colModUser": "ModUser",

  "colDivision": "Division",
  "colRuleName": "RuleName",
  "colRuleId": "RuleId",
  "colInfo": "Info.",
  "colDesc": "Desc.",
  "colThemeName": "Theme",

  "colDeptNm": "Dept",
  "colLoginDate": "LastLoginDate",
  "colLoginClient": "LastLoginClient",

  // options
  "optDate": "Date",
  "searchStartDate": "From-Date",
  "searchEndDate": "To-Date",
  "optDivision": "Division",
  "optViolatedDivision": "ViolatedDiv",

  "optClientStatus": "ClientStatus",
  "optKeyword": "Keyword",

  // Buttons
  "btnSearch": "Search",
  "btnRegist": "Regist",
  "btnSave": "Save",
  "btnClose": "Close",
  "btnCreate": "Create",
  "btnAdd": "Add",
  "btnCopy": "Copy",
  "btnSelect": "Select",
  "btnSelectFile": "FileSelect",

  // Menus
  "menuDashboard": "Dashboard",
  "menuStatistic": "Statistic",
  "menuDailyViolated": "DailyViolatedStatics",
  "menuDailyConnected": "DailyConnectedStatics",
  "menuDailyRegistered": "DailyRegisteredStatics",
  "menuSecurityLog": "SecurityLog",

  "menuClient": "Client",
  "menuClientManage": "ClientMng",
  "menuClientRegKey": "RegKeyMng",
  "menuClientRule": "ClientRule",
  "menuClientSetup": "ClientSetup",
  "menuClientHosts": "HOSTS",
  "menuClientUpdateServer": "UpdateServer",

  "menuSoftware": "Software",
  "menuPackageManage": "PackageMng",
  "menuProfileManage": "ProfileMng",

  "menuUser": "User",
  "menuUserManage": "UserMng",

  "menuUseRule": "ClientUseRule",
  "menuMediaRuleManage": "MediaRule",
  "menuBrowserRuleManage": "BrowserRule",
  "menuSecurityRuleManage": "SecurityRule",
  "menuSoftwareRuleManage": "SoftwareRule",
  
  "menuDesktop": "Desktop",
  "menuDesktopManage": "DesktopMng",
  "menuDesktopAppManage": "DesktopAppMng",
  "menuCloudServiceManage": "CloudServiceMng",
  "menuThemeManage": "ThemeMng",

  "menuJob": "Job",
  "menuJobManage": "JobMng",

  // 공통
  "selOffline": "Offline",
  "selOnline": "Online",
  "selViolated": "Violated",
  "selUnviolated": "Unviolated",
  "lbDesc": "Desc.",
  "lbName": "Name",
  "lbId": "ID",
  "lbClientId": "ClientId",
  "dtSystemError": "System Error",
  "dtSystemNotice": "System Notice",
  "dtEditOK": "Edit Success",
  "selBasic": "Basic",
  "selOrdinary": "Ordinary",
  "msgInputName": "Please enter your name.",
  "selDelete": "Delete",
  "selNoDelete": "NoDelete",
  "msgCopyRule": "Would you like to copy this rule and create a new one?",
  "dtCopy": "Copy",
  "dtApply": "Apply",
  "msgApplyRuleToChild": "Do you want to apply this rule to suborganizations?",
  "dtNameAndId": "Name(ID)",
  "selNoSelected": "NoSelect",
  "msgShowSpecAsSelectRule": "When you select the rule information, details are displayed.",


  // 일별접속통계
  "connectRequestCount": "ConnReqCnt",
  "connReqUserCount": "ConnReq UserCnt",
  "connReqClientCount": "ConnReq ClientCnt",
  "connSuccessCount": "ConnSuccCnt",
  "connFailCount": "ConnFailCnt",

  // 단말등록통계
  "regClientCount": "RegClientCnt",
  "revokeClientCount": "RevokeClientCnt",

  // 단말관리
  "ttAddNewGroup": "Create New Group",
  "ttDeleteGroup": "Delete Group",
  "ttAddClientInGroup": "Add Client To Group",
  "ttDeleteClientFromGroup": "Delete Client From Group",
  "ttRevokeClient": "Revoke Client",

  "spClientGroup": "Client Group",
  "spClientDesc": "Client Desc.",
  "spClientGroupName": "Group Name",
  "spClientGroupDesc": "Group Desc",
  "spIsOnline": "Is Online",
  "spHomeSizeRate": "Home Use Rate",
  "spInstalledPkgCnt": "Installed Package Cnt",
  "spBootViolated": "Boot Violated",
  "spExeViolated": "Exe Violated",
  "spMediaViolated": "Media Violated",
  "spOSViolated": "OS Violated",
  "spClientRegDate": "Client Reg Date",
  "msgRevokedClient": "this is revoked client.",

  "dtDeleteClient": "Client Delete",
  "msgDeleteClient": "단말({{clientCnt}}개)을 삭제하시겠습니까?",

  "dtAddGroup": "Client Group Register",
  "dtEditGroup": "Client Group Edit",
  "dtDeleteGroup": "Client Group Delete",
  "msgDeleteGroup": "단말그룹({{groupCnt}}개)을 삭제하시겠습니까?",
  "dtViewGroup": "Client Group Information",
  "dtAddClientInGroup": "Add Client To Group",
  "msgAddClientInGroup": "선택한 단말({{clientCnt}}개)을 단말그룹('{{groupName}}')으로 변경하시겠습니까?",
  "dtDeleteClientFromGroup": "Delete Client From Group",

  "msgAddGroup": "Do you want to register the client group?",
  "msgEditGroup": "Do you want to edit the client group?",
  "msgDeleteGroup": "Do you want to delete the client group?",
  "msgInputGroupName": "Please enter a client group name.",
  "msgSelectClient": "Please select a client.",
  "msgCfmDeleteClientFromGroup": "Are you sure you want to delete the selected client from the group?",
  "msgCfmSelectGroupForInsertClient": "Select the group to which you want to add the client.",

  // 단말 등록키 관리
  "dtAddClientKey": "단말 등록키 등록",
  "msgAddClientKey": "단말등록키를 등록하시겠습니까?",
  "dtEditClientKey": "단말 등록키 수정",
  "msgEditClientKey": "단말등록키를 수정하시겠습니까?",
  "dtDeleteClientKey": "단말 등록키 삭제",
  "msgDeleteClientKey": "단말등록키 ('{{regKeyNo}}')을 삭제하시겠습니까?",
  "dtViewClientKey": "단말 등록키 정보",
  "msgCopyedIntoClipboard": "단말등록키가 클립보드에 복사되었습니다. 붙여넣기 하실 수 있습니다.",
  "spClientRegKey": "등록키",
  "msgCreateClientRegKey": "단말 등록키를 생성하세요.",
  "btnCreateClientRegKey": "키생성",
  "btnCopyToClipboard": "복사하기",
  "colKeyValidDate": "유효날짜",
  "colCertExpireDate": "인증서만료날짜",
  "lbKeyValidDate": "유효날짜",
  "lbCertExpireDate": "인증서만료날짜",
  "lbValidRegIp": "유효 IP 범위",
  "msgInputValidIp": "유효 아이피를 입력하세요.",
  "msgHelpInputIp": "여러개인 경우 콤마(.) 로 구분, 또는 "-" 로 영역 설정 가능합니다.",
  "msgSampleIputIp": "(샘플) '127.0.0.1, 169.0.0.1' 또는 '127.0.0.1 - 127.0.0.10'",

  // 프로파일정보
  "dtExecuteClientProfile": "단말프로파일 실행",
  "msgExecuteClientProfile": "단말프로파일을 실행하시겠습니까?",
  "dtAddClientProfile": "단말프로파일 등록",
  "msgAddClientProfile": "단말프로파일을 등록하시겠습니까?",
  "dtEditClientProfile": "단말프로파일 수정",
  "msgEditClientProfile": "단말프로파일을 수정하시겠습니까?",
  "dtDeleteClientProfile": "단말프로파일 삭제",
  "msgDeleteClientProfile": "단말프로파일 ('{{profileNo}}')를 삭제하시겠습니까?",
  "dtViewClientProfile": "단말프로파일 정보",
  "lbProfileName": "프로파일 이름",
  "msgInputProfileName": "프로파일 이름을 입력하세요.",
  "lbProfileDesc": "프로파일 설명",
  "lbProfileEtcHandle": "기타 패키지 처리방식",
  "lbReferenceClient": "레퍼런스 단말",
  "msgSelectRefClient": "레퍼런스 단말을 선택하세요.",
  "msgSelectClientInBelow": "아래 목록에서 단말을 선택하세요.",
  "lbTargetClient": "대상 단말",
  "lbPackageInfo": "패키지 정보",
  
  // 패키지관리
  "selShowDiffPackage": "차이있는 패키지만 보기",
  "selShowAllPackage": "전체 패키지 보기",
  "ttPackageUpdate": "패키지 업데이트",
  "ttPackageDelete": "패키지 삭제",
  "dtPackageUpdate": "패키지 업데이트",
  "msgPackageUpdate": "패키지({{packageCnt}}개)를 업데이트하시겠습니까?",
  "dtPackageDelete": "패키지 삭제",
  "msgPackageDelete": "패키지({{packageCnt}}개)를 삭제하시겠습니까?",
  "msgCreatePkgUpdateJob": "패키지 업데이트 작업이 생성되었습니다.",
  "msgNoCreatePkgUpdateJob": "패키지 업데이트 작업이 생성되지 못하였습니다.",
  "msgCreatePkgDeleteJob": "패키지 삭제 작업이 생성되었습니다.",
  "msgNoCreatePkgDeleteJob": "패키지 삭제 작업이 생성되지 못하였습니다.",
  "btnAllUpdate": "전체업데이트",
  "btnAddPackage": "패키지추가",
  "dtInstallSelectedPackage": "선택한 패키지 설치",
  "msgInstallSelectedPackage": "선택한 패키지를 설치하시겠습니까?",
  "dtAllPackageUpadte": "전체패키지 업데이트",
  "msgAllPackageUpadte": "선택하신 단말 또는 그룹에 업데이트 가능 패키지를 모두 업데이트 하겠습니까?",
  "msgSelectClientForUpdate": "패키지를 설치할 단말을 선택하세요.",
  "dtAddClientPackage": "단말패키지 등록",
  "msgAddClientPackage": "단말패키지를 등록하시겠습니까?",
  "dtEditClientPackage": "단말패키지 수정",
  "msgEditClientPackage": "단말패키지를 수정하시겠습니까?",
  "dtViewClientPackage": "단말패키지 정보",
  "lbPackageName": "단말패키지 이름",
  "lbPackageDesc": "단말패키지 설명",

  // 작업관리
  "dtJobStatus": "작업상태",
  "msgNoResult": "결과가 없습니다.",
  "dtJobModule": "모듈",
  "dtJobTask": "타스크",
  "dtJobMessage": "메세지",
  "dtJobInfo": "작업정보",
  "dtJobNo": "작업번호",
  "dtJobName": "작업이름",
  "dtJobRegDate": "작업생성일",
  "dtJobTargetResult": "작업대상 결과정보",
  "dtJobResultStatus": "작업상태(결과)",
  "dtJobModuleInfo": "작업모듈 정보",
  "btnCancelJob": "작업취소",
  "dtCancelJob": "작업 취소",
  "msgCancelJob": "작업대상 단말중 '작업전' 상태 단말의 작업을 취소하시겠습니까?",

  // 단말정책설정
  "dtAddClientConf": "단말정책설정 등록",
  "msgAddClientConf": "단말정책설정를 등록하시겠습니까?",
  "dtEditClientConf": "단말정책설정 수정",
  "msgEditClientConf": "단말정책설정를 수정하시겠습니까?",
  "dtCopyClientConf": "단말정책설정 복사",
  "msgCopyClientConf": "단말정책설정를 복사하였습니다.",
  "dtViewClientConf": "단말정책설정 정보",
  "dtOSProtect": "운영체제보호",
  "dtInitHomeFolder": "홈폴더 초기화",
  "dtTrustedBoot": "신뢰부팅",
  "dtExeProtect": "실행파일보호",
  "dtMediaProtect": "매체제어",
  "dtAgent": "에이전트",
  "selStop": "중단",
  "selRun": "구동",
  "selExecute": "실행",
  "lbViolatedLogLebel": "침해 로그레벨(수준)",
  "lbClientLogLevel": "단말 로그보기에 표시되는 로그레벨(수준)",
  "lbServerLogLevel": "서버로 전송하는 로그레벨(수준)",
  "lbDeleteAfterSend": "전송후 삭제여부",
  "lbSaveDateAfterSend": "서버전송후 로그보관일수",
  "msgHelpNoDeleteIfZero": "'0' 으로 설정시 삭제하지 않음",
  "dtClientLogSetup": "단말 로그 (JournalD Log) 설정",
  "lbLogFileMax": "로그파일 최대크기(MB)",
  "msgCreateNewFileIfMax": "최대크기에 도달하면 새로운 파일을 생성",
  "msgMegabateUnit": "단위는 Mega-Byte",
  "lbSavedLogFileCount": "보관할 로그파일 갯수",
  "msgDeleteFileIfOverCount": "갯수가 초과되면 오래된 파일을 삭제",
  "lbMinimumDiskSizeRate": "최소 확보 디스크 공간(%)",
  "msgHelpMinimumDiskSizeRate": "단위는 '%'이며 디폴트는 '10%'",
  "msgHelpDiskSizeData": "저널디의 'SystemKeepFree' 설정값",
  "dtSetupConnectableIp": "접속 가능 아이피 설정",
  "dtPermitAllIp": "전체 아이피 허용",
  "selPermit": "허용함",
  "selNoPermit": "허용안함",
  "dtSetupLogLevel": "로그레벨 설정",
  "dtIsUseDeleteFunc": "삭제기능 사용여부",
  "lbSetupClient": "단말 설정",

  // 데스크톱앱관리
  "dtDeleteDesktopApp": "데스크톱앱 삭제",
  "msgDeleteDesktopApp": "데스크톱앱('{{appId}}') 을 삭제하시겠습니까?",
  "dtAddDesktopApp": "데스크톱앱 등록",
  "msgAddDesktopApp": "데스크톱앱을 등록하시겠습니까?",
  "dtEditDesktopApp": "데스크톱앱 수정",
  "msgEditDesktopApp": "데스크톱앱을 수정하시겠습니까?",
  "msgCopyDesktopApp": "데스크톱앱을 복사하였습니다.",
  "dtViewDesktopApp": "데스크톱앱 정보",
  "dtCopyDesktopApp": "데스크톱앱 복사",
  "lbDesktopAppType": "데스크톱앱 종류",
  "lbMountApp": "마운트앱",
  "lbExecuteCmd": "실행 명령어",
  "lbMountUrl": "마운트 URL",
  "lbMountPoint": "마운트 포인트",
  "lbServiceStatus": "서비스 상태",
  "selSeviceOn": "사용",
  "selSeviceOff": "중지",
  "lbIconDivision": "ICON 구분",
  "lbIconInfo": "ICON 정보",
  "lbUseFavicon": "Favicon 사용",
  "lbUseIconLib": "라이브러리 사용",
  "lbFaviconUrl": "Favicon URL",
  "lbIconType": "ICON 타입",
  "lbIconEditDate": "수정일",
  "msgHelpDeleteApp": "현재 데스크톱 앱 삭제는 '데스크톱앱관리' 메뉴에서만 실행 되도록 설정되어 있습니다.",
  "msgAppList": "앱리스트 (아래 전체앱리스트에서 앱을 추가할 수 있습니다.)",
  "lbAppAllList": "전체 앱 리스트",

  // 데스크톱정보 관리
  "dtDeleteDesktopConf": "데스크톱정보 삭제",
  "msgDeleteDesktopConf": "데스크톱정보('{{confId}}')를 삭제하시겠습니까?",
  "dtAddDesktopConf": "데스크톱정보 등록",
  "msgAddDesktopConf": "데스크톱정보를 등록하시겠습니까?",
  "dtEditDesktopConf": "데스크톱정보 수정",
  "msgEditDesktopConf": "데스크톱정보를 수정하시겠습니까?",
  "msgApplyDesktopConfToChild": "데스크톱정보가 하위 조직에 적용되었습니다.",
  "dtCopyDesktopConf": "데스크톱정보 복사",
  "msgCopyDesktopConf": "데스크톱정보를 복사하였습니다.",
  "dtViewDesktopConf": "데스크톱정보 정보",
  "dtInheritDesktopConf": "데스크톱정보 상속",
  "lbTheme": "테마",
  "lbDesktopConf": "데스크톱정보",

    // 사용자관리
    "ttAddNewDept": "신규조직등록",
    "ttDeleteDept": "조직삭제",
    "ttChangMultiDeptRule": "조직정책 일괄변경",
    "ttAddUserInDept": "조직에 사용자 추가",
    "ttDeleteUserInDept": "조직에서 사용자 삭제",
    "ttMoveDept": "부서이동",
    "ttAddUser": "신규사용자 생성",
    "dtAddUser": "사용자 등록",
    "dtViewUser": "사용자 정보",
    "dtEditUser": "사용자 수정",
    "dtAddDept": "조직 등록",
    "dtViewDept": "조직 정보",
    "dtEditDept": "조직 수정",
    "dtSelectDept": "조직 선택",
    "dtChangDeptMultiple": "조직 일괄 변경",
    "lbUserId": "사용자아이디",
    "lbPassword": "Password",
    "lbUserName": "사용자이름",
    "lbDept": "조직",
    "lbParentDept": "상위조직",
    "msgEnterUserName": "사용자이름을 입력하세요.",
    "msgSelectDept": "조직을 선택하세요.",
    "msgEnterUserId": "사용자아이디를 입력하세요.",
    "msgUserIdValid": "알파벳 또는 숫자만 입력하세요.",
    "msgEnterPassword": "password를 입력하세요.",
    "msgSelectParentDept": "상위 조직을 선택 하세요.",
    "msgSelectDeptForAddUser": "사용자를 추가할 조직을 선택하세요.",
    "msgSelectUser": "사용자를 선택하세요.",
    "lbDeleteUser": "사용자 삭제",
    "msgDeleteUser": "선택하신 사용자를 조직에서 삭제하시겠습니까?",
    "lbChangeDeptForUser": "사용자 조직 변경",
    "msgChangeDeptForUser": "선택한 사용자({{userCnt}}명)를 조직('{{deptNm}}')으로 변경하시겠습니까?",
    "lbAddUserInDept": "조직('{{deptNm}}')에 사용자 추가",
    "lbDeleteUserInfo": "사용자정보 삭제",
    "msgDeleteUserInfo": "사용자정보('{{userNm}}')을 삭제하시겠습니까?",
    "lbAddUserInfo": "사용자정보 등록",
    "msgAddUserInfo": "사용자정보를 등록하시겠습니까?",
    "lbEditUserInfo": "사용자정보 수정",
    "msgEditUserInfo": "사용자정보를 수정하시겠습니까?",
    "msgChangeDeptRuleSelected": "선택하신 조직의 정책정보를 수정하시겠습니까?",
    "lbDeptId": "조직아이디",
    "lbDeptName": "조직이름",
    "msgEnterDeptName": "조직이름을 입력하세요.",
    "msgEnterDeptId": "조직아이디를 입력하세요.",
    "msgDeptIdValid": "알파벳,숫자,'-','_','.' 문자만 입력하세요.",
    "lbEditDeptInfo": "조직정보 수정",
    "msgEditDeptInfo": "조직정보를 수정하시겠습니까?",
    "lbEditChildDeptInfo": "하위조직 적용여부",
    "lbAddDeptInfo": "조직정보 등록",
    "msgAddDeptInfo": "조직정보를 등록하시겠습니까?",
  
    // 테마관리
    "lbDeleteTheme": "테마 삭제",
    "msgDeleteTheme": "테마('{{themeNm}}')를 삭제하시겠습니까?",
    "lbAddTheme": "테마 등록",
    "msgAddTheme": "테마를 등록하시겠습니까?",
    "lbEditTheme": "테마 수정",
    "msgEditTheme": "테마를 수정하시겠습니까?",
    "dtAddTheme": "테마 등록",
    "dtViewTheme": "테마 정보",
    "dtEditTheme": "테마 수정",
    "lbThemeId": "테마아이디",
    "lbThemeName": "테마 이름",
    "msgThemeName": "테마 이름을 입력하세요.",
    "lbThemeDesc": "테마 설명",
    "lbIconSetting": "업무환경(Application) 아이콘 설정",
    
    // 관리서버설정
    "lbSaveServerConfig": "구름관리서버설정 저장",
    "msgSaveServerConfig": "구름관리서버설정을 저장하시겠습니까?",
    "msgEditOkServerConfig": "구름관리서버설정이 저장되었습니다.",
    "msgEditErrorServerConfig": "구름관리서버설정이 저장되지 않았습니다.",
    "lbServerInfo": "서버 정보",
    "lbGPMSServerInfo": "GPMS 정보",
    "lbGLMServerInfo": "GLM 정보",
    "lbGRMServerInfo": "GRM 정보",
    "lbAgentPollingTime": "구름 Agent 폴링 타임",
    "msgAgentPollingTime": "구름단말 Agent 와 GRM 서버간의 정보교환 주기",
  
    // 클라우드서비스 관리
    "lbDeleteCloudService": "클라우드서비스 삭제",
    "msgDeleteCloudService": "클라우드서비스('{{gcspId}}')를 삭제하시겠습니까?",
    "lbAddCloudService": "클라우드서비스 등록",
    "msgAddCloudService": "클라우드서비스를 등록하시겠습니까?",
    "lbEditCloudService": "클라우드서비스 수정",
    "msgEditCloudService": "클라우드서비스를 수정하시겠습니까?",
    "dtAddCloudService": "클라우드서비스 등록",
    "dtViewCloudService": "클라우드서비스 정보",
    "dtEditCloudService": "클라우드서비스 수정",
    "lbCloudServiceId": "서비스아이디",
    "msgCloudServiceId": "서비스아이디를 입력하세요.",
    "msgValidCloudServiceId": "알파벳,숫자,'-','_','.' 문자만 입력하세요.",
    "lbCloudServiceName": "서비스이름",
    "msgCloudServiceName": "서비스이름을 입력하세요.",
    "lbCloudServiceDesc": "서비스설명",
    "lbCloudServiceIp": "접근가능 IP",
    "lbCloudServiceDomain": "서비스 도메인",
    "lbCreateCertType": "인증서 생성 방법",
    "selAutoCreateCert": "자동 생성",
    "msgAutoCreateCert": "구름서버에서 인증서를 자동으로 생성합니다.",
    "selCSRCreateCert": "CSR 생성",
    "msgCSRCreateCert": "CSR정보를 이용하여 인증서를 승인합니다.",
    "lbCSRInfo": "CSR 정보",
    "lbCertInfo": "인증서 정보",
    "lbCert": "인증서",
    "lbPrivateKey": "개인키",
  
    // 관리자 관리 
    "btConnIpMng": "접속아이피관리",
    "lbDeleteAdminUser": "관리자계정 삭제",
    "msgDeleteAdminUser": "관리자계정('{{adminId}}')을 삭제하시겠습니까?",
    "lbAddAdminUser": "관리자계정 등록",
    "msgAddAdminUser": "관리자계정을 등록하시겠습니까?",
    "lbEditAdminUser": "관리자계정 수정",
    "msgEditAdminUser": "관리자계정을 수정하시겠습니까?",
    "dtAddAdminUser": "관리자계정 등록",
    "dtViewAdminUser": "관리자계정 정보",
    "dtEditAdminUser": "관리자계정 수정",
    "lbAdminUserId": "관리자아이디",
    "msgAdminUserId": "관리자아이디를 입력하세요.",
    "msgValidAdminUserId": "알파벳 또는 숫자만 입력하세요.",
    "lbAdminUserName": "관리자이름",
    "msgAdminUserName": "관리자이름을 입력하세요.",
    "lbAdminPassowrd": "Password",
    "msgAdminPassword": "password를 입력하세요.",
    "lbAdminConnIp": "관리자 접속 가능 아이피",
    "msgAdminConnIp": "아이피 또는 도메인을 입력하세요.",
    "msgValidAdminConnIp": "알파벳,숫자,'.' 문자만 입력하세요.",
    "lbSaveAdminConnIp": "접속가능 아이피 저장",
    "msgSaveAdminConnIp": "접속가능 아이피 정보를 저장하시겠습니까?",
    "dtAdminJobHist": "관리자({{adminId}}) 작업 이력",

    


    
};
