export default {
  "gpmsTest": "Community",
  "adminMenu": "ADMIN",

  // columns
  "colDate": "DATE",
  "colNumber": "No",
  "colName": "Name",
  "colConnReqCount": "ReqCnt",
  "colConnSuccess": "ConnSuccCnt",
  "colConnFail": "ConnFailCnt",
  "colConnRequest": "ConnReqCnt",
  "colConnRequests": "ConnRequest",
  "colConnRequestUser": "UserConnRequest",
  "colConnRequestClient": "ClientConnRequest",

  "colBootViolated": "BootViolated",
  "colExeViolated": "ExeViolated",
  "colOSViolated": "OSViolated",
  "colMediaViolated": "MediaViolated",

  "colRegCount": "RegCnt",
  "colRevokeCount": "RevokeCnt",
  "colWorkCount": "WorkCnt",

  "colClientId": " ClientId",
  "colClientName": "ClientName",
  "colClientGroup": "ClientGroup",
  "colGroupName": "GroupName",
  "colClientCount": "ClientCnt",
  "colDeptName": "DeptName",
  "colUser": "User",
  "colUserId": "UserId",
  "colUserNm": "UserName",
  "colUserCount": "UserCnt",
  "colLogType": "LogType",
  "colLogInfo": "LogInfo",
  "colRegDate": "RegDate",
  "colModDate": "ModDate",
  "colStatus": "Status",
  "colEdit": "Edit",
  "colEditDelete": "Edit/Del",
  "colCreateUser": "Creator",

  "colId": "ID",
  "colLastLoginDate": "LastLoginDate",
  "colLastLoginIp": "LastLoginIp",
  "colLoginId": "LoginId",
  "colUseRate": "UseRate",

  "colClientRegKey": "ClientRegKey",
  "colKeyValidDate": "ValidDate",
  "colCertExpireDate": "ExpireDate",

  "colRefClientId": "RefClient",
  "colProfile": "Profile",
  "colPackageInfo": "PackageInfo",
  "colPackageName": "PackageName",
  "colPackageUpdateCnt": "UpdateCnt",
  "colPackageCnt": "PackageCnt",

  "colArchitecture": "Architecture",
  "colInstalledVersion": "InstalledVer.",
  "colVersion": "Version",
  "colAvailVersion": "AvailableVer.",

  "colJobNo": "JobNo",
  "colJobName": "JobName",
  "colJobHistory": "JobHistory",
  "colJobStatus": "Status",
  "colReqJob": "ReqJob",
  "colJobType": "JobType",
  "colJobProgressStatus": "Status",
  "colTargetCnt": "TargetCnt",
  "colJobErrorCnt": "ErrorCnt",
  "colJobCompCnt": "CompCnt",
  "colRegUser": "RegUser",
  "colModUser": "ModUser",

  "colDivision": "Division",
  "colRuleName": "RuleName",
  "colRuleId": "RuleId",
  "colInfo": "Info.",
  "colDesc": "Desc.",
  "colThemeName": "Theme",

  "colDeptNm": "Dept",
  "colLoginDate": "LastLoginDate",
  "colLoginClient": "LastLoginClient",
  "colViolatedCnt": "VioratedCnt",

  "colBootProtect": "BootProtect",
  "colExeProtect": "ExeProtect",
  "colOSProtect": "OSProtect",
  "colMediaProtect": "MediaProtect",
  "colRepair": "Repair",
  "colViolateStatus": "ViolateStatus",
  "colViolateRun": "Prtector Func. Run",

  "colTitle": "Title",
  "colContent": "Content",
  "colRegUserId": "Created Admin",

  "colType": "Type",
  "colTargetDept": "Dept",
  "colTargetGroup": "Group",
  "colMngClient": "MngClient",
  "colMngUser": "MngUser",
  "colMngDesktop": "MngDesktop",
  "colMngNotify": "MngNotify",
  "colActHistory": "History",

  "colLogNo": "LogNo",
  "colLogDate": "LogDate",
  "colLogType": "LogType",
  "colAccessIp": "AccessIp",
  "colLogItem": "LogItem",
  "colLogData": "LogData",

  // options
  "optDate": "Date",
  "searchStartDate": "From-Date",
  "searchEndDate": "To-Date",
  "optDivision": "Division",
  "optViolatedDivision": "ViolatedDiv",
  "expireDate": "Expire-Date",

  "optClientStatus": "ClientStatus",
  "optKeyword": "Keyword",

  "optMinutes" : "Min",
  "optHours" : "Hours",

  "optUse" : "Use",
  "optNoUse" : "No Use",

  // Buttons
  "btnSearch": "Search",
  "btnRegist": "Regist",
  "btnSave": "Save",
  "btnClose": "Close",
  "btnCreate": "Create",
  "btnAdd": "Add",
  "btnCopy": "Copy",
  "btnSelect": "Select",
  "btnSelectFile": "FileSelect",
  "btnOK": "OK",
  "btnYes": "Yes",
  "btnNo": "No",

  // Menus
  "home": "",
  "menuDashboard": "Dashboard",
  "menuStatistic": "Statistic",
  "menuDailyViolated": "DailyViolatedStatics",
  "menuDailyConnected": "DailyConnectedStatics",
  "menuDailyRegistered": "DailyRegisteredStatics",
  "menuSecurityLog": "SecurityLog",

  "menuClient": "Client",
  "menuClientManage": "ClientMng",
  "menuClientRegKey": "RegKeyMng",
  "menuClientRule": "ClientRule",
  "menuClientSetup": "ClientSetup",
  "menuClientHosts": "HOSTS",
  "menuClientUpdateServer": "UpdateServer",

  "menuSoftware": "Software",
  "menuPackageManage": "PackageMng",
  "menuProfileManage": "ProfileMng",

  "menuUser": "User",
  "menuUserManage": "UserMng",

  "menuUseRule": "RuleManage",
  "menuMediaRuleManage": "MediaRule",
  "menuBrowserRuleManage": "BrowserRule",
  "menuSecurityRuleManage": "SecurityRule",
  "menuSoftwareRuleManage": "SoftwareRule",

  "menuDesktop": "Desktop",
  "menuDesktopManage": "DesktopMng",
  "menuDesktopAppManage": "DesktopAppMng",
  "menuCloudServiceManage": "CloudServiceMng",
  "menuThemeManage": "ThemeMng",

  "menuJob": "Job",
  "menuJobManage": "JobMng",

  "menuSiteConfig": "GPMS settings",
  "menuAdminUserMng": "Admin Mng.",
  "menuDeptAndUser": "Dept/User Batch registration",

  // 공통
  "selOffline": "Offline",
  "selOnline": "Online",
  "selViolated": "Violated",
  "selUnviolated": "Unviolated",
  "lbDesc": "Desc.",
  "lbName": "Name",
  "lbId": "ID",
  "lbClientId": "ClientId",
  "lbClientName": "ClientName",
  "dtSystemError": "System Error",
  "dtSystemNotice": "System Notice",
  "dtEditOK": "Edit Success",
  "selBasic": "Basic",
  "selStandard": "Standard",
  "selOrdinary": "Ordinary",
  "msgInputName": "Please enter name.",
  "selDelete": "Delete",
  "selNoDelete": "NoDelete",
  "msgCopyRule": "Would you like to copy this rule and create a new one?",
  "dtCopy": "Copy",
  "dtApply": "Apply",
  "msgApplyRuleToChild": "Do you want to apply this rule to suborganizations?",
  "dtNameAndId": "Name(ID)",
  "selNoSelected": "NoSelect",
  "msgShowSpecAsSelectRule": "When you select the rule information, details are displayed.",
  "lbDefaultRule": "Default Rule",
  "lbClientGroupRule": "Client Group Rule",
  "lbDeptRule": "Dept. Rule",
  "lbUserRule": "User Rule",
  "lbClientSelect": "Select Client",
  "msgTypeNumberOnly": "Please enter only numbers.",
  "msgInvalidMacAddress": "The MAC address is not correct.",
  "msgInvalidNumber":"Please enter setting value.",
  "msgInvalidValue": "Please enter a valid setting value.",
  "lbSelectAll": "Select All",

  // options
  "stBeforeJob": "Before",
  "stCompJob": "Complete",
  "stRunningJob": "Running",
  "stFailJob": "Fail",
  "stCancelJob": "Cancel",
  "stRevokeClient": "Revoked",
  "stNormal": "Normal",
  "stDelete": "Delete",
  "stAll": "All",
  "stNormalClient": "Normal",
  "stViolatedClient": "Violated",
  "stRevokedClient": "Revoked",
  "stOnlineClient": "Online",
  "stBrowser": "Browser",
  "stAgent": "Agent",
  "stMediaProctect": "Media",
  "stOSProctect": "OS",
  "stExeProctect": "Execute",
  "stBootProctect": "Booting",
  "stAgentProctect": "Agent",
  "stEmergLevel": "",
  "stAlertLevel": "",
  "stCritLevel": "",
  "stErrLevel": "",
  "stWarningLevel": "",
  "stInfoLevel": "",
  "stDebugLevel": "",

  "stNoUse": "Ignore",
  "stNoticeLevel": "Alarm",
  "stShowLevel": "Show",
  "stTranmitLevel": "Transmit",

  // 일별접속통계
  "connectRequestCount": "ConnReqCnt",
  "connReqUserCount": "ConnReq UserCnt",
  "connReqClientCount": "ConnReq ClientCnt",
  "connSuccessCount": "ConnSuccCnt",
  "connFailCount": "ConnFailCnt",

  // 단말등록통계
  "regClientCount": "RegCnt",
  "revokeClientCount": "RevokeCnt",

  // 단말관리
  "ttAddNewGroup": "Create New Group",
  "ttDeleteGroup": "Delete Group",
  "ttAddClientInGroup": "Add Client To Group",
  "ttDeleteClientFromGroup": "Delete Client From Group",
  "ttRevokeClient": "Revoke Client",

  "spClientGroup": "Client Group",
  "spClientDesc": "Client Desc.",
  "spClientStatus": "Client Status",
  "spClientGroupName": "Group Name",
  "spClientGroupDesc": "Group Desc",
  "spIsOnline": "Is Online",
  "spHomeSizeRate": "Home Use Rate",
  "spInstalledPkgCnt": "Installed Package Cnt",
  "spBootViolated": "Boot Violated",
  "spExeViolated": "Exe Violated",
  "spMediaViolated": "Media Violated",
  "spOSViolated": "OS Violated",
  "spClientRegDate": "Client Reg Date",
  "msgRevokedClient": "this is revoked client.",

  "dtDeleteClient": "Client Delete",
  "msgDeleteClient": "Are you sure you want to delete the {{clientCnt}} clients?",

  "dtAddGroup": "Client Group Register",
  "dtEditGroup": "Client Group Edit",
  "dtDeleteGroup": "Client Group Delete",
  "msgDeleteGroup": "Are you sure you want to delete {{groupCnt}} client groups? (except default)",
  "lbDeleteInClient": "Whether client in the group is deleted",
  "dtViewGroup": "Client Group Information",
  "dtAddClientInGroup": "Add Client To Group",
  "msgAddClientInGroup": "Are you sure you want to change the selected clients ({{clientCnt}}) to the client group ('{{groupName}}')?",
  "dtDeleteClientFromGroup": "Delete Client From Group",
  "dtChangGroupMultiple": "Change Client Group batch",

  "msgAddGroup": "Do you want to register the client group?",
  "msgEditGroup": "Do you want to edit the client group?",
  "msgInputGroupName": "Please enter a client group name.",
  "msgSelectClient": "Please select a client.",
  "msgSelectClientGroup": "Please select a client group.",
  "msgCfmDeleteClientFromGroup": "Are you sure you want to delete the selected client from the group?",
  "msgCfmSelectGroupForInsertClient": "Select the group to which you want to add the client.",
  "dtSelectClient": "Client selection",

  "ttUpdateTotalPackgeInClient": "Updating the entire package in Client",
  "ttUpdateSelectedPackgeInClient": "Update selected package on Client",
  "ttUpdateTotalPackgeInGroup": "Updating the entire package in Client Group",
  "ttUpdateSelectedPackgeInGroup": "Update selected package on Client Group",

  // 단말 등록키 관리
  "dtAddClientKey": "Registration of client registration key",
  "msgAddClientKey": "Do you want to register the client registration key?",
  "dtEditClientKey": "Modify client registration key",
  "msgEditClientKey": "Do you want to modify the client registration key?",
  "dtDeleteClientKey": "Delete client registration key",
  "msgDeleteClientKey": "Are you sure you want to delete the client registration key ('{{regKeyNo}}')?",
  "dtViewClientKey": "The client registration key information",
  "msgCopyedIntoClipboard": "The client registration key has been copied to the clipboard. You can paste.",
  "spClientRegKey": "Registration key",
  "msgCreateClientRegKey": "Create a client registration key.",
  "btnCreateClientRegKey": "KeyGeneration",
  "btnCopyToClipboard": "Copy",
  "lbKeyValidDate": "Effective Date",
  "lbCertExpireDate": "Certificate expiration date",
  "lbValidRegIp": "Effective IP Range",
  "msgInputValidIp": "Please enter a valid IP address.",
  "msgHelpInputIp": "If you have more than one, you can use commas (.) Or '-'.",
  "msgSampleIputIp": "(Sample) '127.0.0.1, 169.0.0.1' Or '127.0.0.1 - 127.0.0.10'",

  // 프로파일정보
  "dtExecuteClientProfile": "Client profile execution",
  "msgExecuteClientProfile": "Do you want to run the client profile?",
  "dtAddClientProfile": "Client profile registration",
  "msgAddClientProfile": "Do you want to register the client profile?",
  "dtEditClientProfile": "Modify client profile",
  "msgEditClientProfile": "Are you sure you want to modify the profile?",
  "dtDeleteClientProfile": "Delete client profile",
  "msgDeleteClientProfile": "Are you sure you want to delete client profile ('{{profileNm}}')?",
  "dtViewClientProfile": "Client profile information",
  "lbProfileName": "Profile Name",
  "msgInputProfileName": "Please enter a profile name.",
  "lbProfileDesc": "Profile description",
  "lbProfileEtcHandle": "Other package handling methods",
  "lbReferenceClient": "Reference client",
  "msgSelectRefClient": "Select a reference client.",
  "msgSelectClientInRight": "Select the terminal using the right button.",
  "lbTargetClient": "Target for Profiling",
  "lbPackageInfo": "Package Information",
  
  // 패키지관리
  "selShowDiffPackage": "View differences",
  "selShowAllPackage": "View all",
  "ttPackageUpdate": "Package Updates",
  "ttPackageDelete": "Delete a package",
  "dtPackageUpdate": "Package Updates",
  "msgPackageUpdate": "Update package {{packageCnt}}?",
  "dtPackageDelete": "Delete a package",
  "msgPackageDelete": "Are you sure you want to remove the package {{packageCnt}}?",
  "msgCreatePkgUpdateJob": "A package update job has been created.",
  "msgNoCreatePkgUpdateJob": "A package update job could not be created.",
  "msgCreatePkgDeleteJob": "A package deletion job has been created.",
  "msgNoCreatePkgDeleteJob": "Failed to create package delete operation.",
  "btnAllUpdate": "Full update",
  "btnAddPackage": "Adding a package",
  "dtInstallSelectedPackage": "Install selected packages",
  "msgInstallSelectedPackage": "Do you want to install the selected packages?",
  "dtAllPackageUpdate": "Update entire package",
  "msgAllPackageUpdate": "Do you want to update all updateable packages to the selected client or group?",
  "msgTotalPackageUpdateForClient": "Do you want to update all updateable packages to the selected client?",
  "msgTotalPackageUpdateForGroup": "Do you want to update all updateable packages to the selected group?",
  "msgSelectClientForUpdate": "Select the client on which you want to install the package.",
  "dtAddClientPackage": "Client package registration",
  "msgAddClientPackage": "Do you want to register the client package?",
  "dtEditClientPackage": "Modify client package",
  "msgEditClientPackage": "Do you want to modify the client package?",
  "dtViewClientPackage": "Client package information",
  "lbPackageName": "Package name",
  "lbPackageDesc": "Package Desc.",
  "dtSelectPackage": "Package Selection",
  "dtAllPackageListUpdate": "Update entire list",
  "btnInstall": "Install",
  "msgNoSelectPackage": "The package to install is not selected.",
  "dtPackageListUpdate": "Update package list",
  "msgPackageListUpdate": "Do you want to update the package list?",
  "dtCompUpdate": "Update completed",
  "msgCompUpdateAndJob": "A task has been created to update the package list. Please wait for 1 ~ 3 minutes before checking.",
  "msgFailCompUpdate": "Package list update job could not be created.",

  // 작업관리
  "dtJobStatus": "Job Status",
  "msgNoResult": "No results found.",
  "dtJobModule": "Module",
  "dtJobTask": "Task",
  "dtJobMessage": "Message",
  "dtJobInfo": "Job Information",
  "dtJobNo": "Job number",
  "dtJobName": "Job name",
  "dtJobRegDate": "Job creation date",
  "dtJobTargetResult": "About the job result",
  "dtJobResultStatus": "Job Status (result)",
  "dtJobModuleInfo": "Job module information",
  "btnCancelJob": "Cancel",
  "dtCancelJob": "Cancel job",
  "msgCancelJob": "Are you sure you want to cancel the operation of the 'Before operation' status client?",

  // 에이전트설정
  "lbClientConf": "AgentSetup",
  "lbClientSetup": "AgentSetup",
  "dtAddClientConf": "Registration of agent setting",
  "msgAddClientConf": "Do you want to register agent settings?",
  "dtEditClientConf": "Edit agent settings",
  "msgEditClientConf": "Are you sure you want to modify agent settings?",
  "dtCopyClientConf": "Copy agent settings",
  "msgCopyClientConf": "The agent settings have been copied.",
  "dtViewClientConf": "Agent setting information",
  "dtOSProtect": "Operating system protection",
  "dtInitHomeFolder": "Initialize home folder",
  "dtTrustedBoot": "Trusted Boot",
  "dtExeProtect": "Protect executable files",
  "dtMediaProtect": "Media control",
  "dtAgent": "Agent",
  "selStop": "Stop",
  "selRun": "Run",
  "selExecute": "Execute",
  "selActive": "Active",
  "selInActive": "InActive",
  "lbViolatedLogLebel": "Infringement log level (level)",
  "lbClientLogLevel": "The log level (level) displayed in the client log view.",
  "lbServerLogLevel": "Log level to send to server (level)",
  "lbDeleteAfterSend": "Delete after transfer",
  "lbSaveDateAfterSend": "Days to keep logs after server transfer",
  "msgRemainFileSettingCount": "Keep log files count as you set",
  "msgHelpNoDeleteIfZero": "If set to '0', do not delete",
  "dtClientLogSetup": "Setting JournalD Log",
  "lbLogFileMax": "Maximum log file size (MB)",
  "msgCreateNewFileIfMax": "Creates a new file when the maximum size is reached",
  "msgMegabateUnit": "The unit is Mega-Byte",
  "lbSavedLogFileCount": "Number of log files to keep",
  "msgDeleteFileIfOverCount": "If the number is exceeded, delete the old file",
  "lbMinimumDiskSizeRate": "Minimum free disk space (%)",
  "msgHelpMinimumDiskSizeRate": "Unit is '%', default is '10%'",
  "msgHelpDiskSizeData": "'SystemKeepFree' setting value of journal-d",
  "dtSetupConnectableIp": "Accessible IP settings",
  "dtPermitAllIp": "Allow entire IP",
  "selPermit": "Allow",
  "selNoPermit": "No allow",
  "dtSetupLogLevel": "Set log level",
  "dtIsUseDeleteFunc": "Whether delete function is used",
  "lbSetupClient": "Agent setting",
  "msgValidOnlyUpperZero": "Only numbers greater than 0 can be entered.",
  "msgValidNumberPeriod": "Input range",

  // 데스크톱앱관리
  "dtDeleteDesktopApp": "Remove desktop app",
  "msgDeleteDesktopApp": "Are you sure you want to delete the desktop app ('{{appId}}')?",
  "dtAddDesktopApp": "Register desktop app",
  "msgAddDesktopApp": "Would you like to register desktop app?",
  "dtEditDesktopApp": "Edit desktop app",
  "msgEditDesktopApp": "Are you sure you want to edit desktop app?",
  "msgCopyDesktopApp": "You have copied desktop app.",
  "dtViewDesktopApp": "About desktop apps",
  "dtCopyDesktopApp": "Copy desktop app",
  "lbDesktopAppType": "Types of desktop apps",
  "lbMountApp": "Mount Apps",
  "lbExecuteCmd": "Execution Commands",
  "lbMountUrl": "Mount URL",
  "lbMountPoint": "Mount Point",
  "lbServiceStatus": "Service status",
  "selSeviceOn": "On",
  "selSeviceOff": "Off",
  "lbIconDivision": "ICON classific",
  "lbIconInfo": "ICON Info",
  "lbUseFavicon": "Use Favicon",
  "lbUseIconLib": "Use Library",
  "lbFaviconUrl": "Favicon URL",
  "lbIconType": "ICON Type",
  "lbIconEditDate": "Modified date",
  "msgHelpDeleteApp": "Currently, Desktop App deletion is set to run only from the 'Desktop App Management' menu.",
  "msgAppList": "App List (You can add apps from the list of all apps below.)",
  "lbAppAllList": "All apps list",

  // 데스크톱정보 관리
  "dtDeleteDesktopConf": "Delete desktop information",
  "msgDeleteDesktopConf": "Are you sure you want to delete desktop information ('{{confId}}')?",
  "dtAddDesktopConf": "Desktop Information Registration",
  "msgAddDesktopConf": "Would you like to register desktop information?",
  "dtEditDesktopConf": "Edit Desktop Information",
  "msgEditDesktopConf": "Are you sure you want to edit desktop information?",
  "msgApplyDesktopConfToChild": "Desktop information has been applied to suborganizations.",
  "dtCopyDesktopConf": "Copy Desktop Information",
  "msgCopyDesktopConf": "I copied the desktop information.",
  "dtViewDesktopConf": "About Desktop Information",
  "dtInheritDesktopConf": "Desktop Information Inheritance",
  "lbTheme": "Theme",
  "lbDesktopConf": "Desktop Information",

  // 사용자관리
  "ttAddNewDept": "New organization registration",
  "ttDeleteDept": "Delete organization",
  "ttChangMultiDeptRule": "Multiple changes to organizational policies",
  "ttAddUserInDept": "Add users to organization",
  "ttDeleteUserInDept": "Remove a user from organization",
  "ttMoveDept": "Move department",
  "ttAddUser": "Create new user",
  "dtAddUser": "User registration",
  "dtViewUser": "User information",
  "dtEditUser": "Edit user",
  "dtAddDept": "Organization registration",
  "dtViewDept": "Organization information",
  "dtEditDept": "Edit Organization",
  "dtSelectDept": "Select organization",
  "dtChangDeptMultiple": "Change organizational batch",
  "lbUserId": "User ID",
  "lbPassword": "Password",
  "lbUserName": "User name",
  "lbEmail": "Email",
  "lbDept": "Organization",
  "lbParentDept": "Parent organization",
  "msgEnterUserName": "Please enter username.",
  "msgSelectDept": "Please select an organization.",
  "msgEnterEmail": "Please enter email.",
  "msgEnterUserId": "Please enter user ID.",
  "msgUserIdValid": "Please enter only lower alphabet characters or numbers.",
  "msgEnterPassword": "Please enter a password.",
  "msgSelectParentDept": "Please select a parent organization.",
  "msgSelectDeptForAddUser": "Please select an organization to add users to.",
  "msgSelectUser": "Please select a user.",
  "lbDeleteUser": "Delete user",
  "msgDeleteUser": "Are you sure you want to remove the selected users from organization?",
  "lbChangeDeptForUser": "Change user organization",
  "msgChangeDeptForUser": "Are you sure you want to change the selected user ({{userCnt}}) to organization ('{{deptNm}}')?",
  "lbAddUserInDept": "Add a user to organization ('{{deptNm}}')",
  "lbDeleteUserInfo": "Delete user information",
  "msgDeleteUserInfo": "Are you sure you want to delete user information ('{{userNm}}')?",
  "lbAddUserInfo": "User information registration",
  "msgAddUserInfo": "Do you want to register user information?",
  "lbEditUserInfo": "Edit user information",
  "msgEditUserInfo": "Do you want to edit user information?",
  "msgChangeDeptRuleSelected": "Are you sure you want to edit the rule information for the selected organization?",
  "lbDeptId": "Organization ID",
  "lbDeptName": "Organization name",
  "msgEnterDeptName": "Please enter an organization name.",
  "msgEnterDeptId": "Please enter an Organization ID.",
  "msgDeptIdValid": "Alphabet, number, '-', '_', '.' Please enter only characters.",
  "lbEditDeptInfo": "Edit Organization Information",
  "msgEditDeptInfo": "Are you sure you want to edit organization information?",
  "lbEditChildDeptInfo": "Whether sub-organizations are applied",
  "lbAddDeptInfo": "Organization information registration",
  "msgAddDeptInfo": "Do you want to register organizational information?",
  "dtDeleteDept": "Delete Organization.",
  "msgDeletedDept": "Are you sure you want to remove the selected organization ({{deptCnt}}ea) ?",
  "lbDeleteInUser": "Whether users in your organization are deleted",
  "lbUseUserExpire": "Whether User Expire Date",
  "lbUserExpireDate": "Expire Date",

  // 테마조회
  "lbDeleteTheme": "Remove theme",
  "msgDeleteTheme": "Are you sure you want to delete the theme ('{{themeNm}}')?",
  "lbAddTheme": "Theme registration",
  "msgAddTheme": "Do you want to register the theme?",
  "lbEditTheme": "Edit theme",
  "msgEditTheme": "Do you want to edit the theme?",
  "dtAddTheme": "Theme registration",
  "dtViewTheme": "Theme Information",
  "dtEditTheme": "Edit theme",
  "lbThemeId": "Theme ID",
  "lbThemeName": "Theme name",
  "msgThemeName": "Please enter a theme name.",
  "lbThemeDesc": "Theme Description",
  "lbIconSetting": "Application icon setting",
  
  // 관리서버설정
  "lbSaveServerConfig": "Save management server settings",
  "msgSaveServerConfig": "Do you want to save the management server settings?",
  "msgEditOkServerConfig": "Management server settings saved.",
  "msgEditErrorServerConfig": "Management server settings are not saved.",
  "lbServerInfo": "Server Information",
  "lbGPMSServerInfo": "GPMS Information",
  "lbGLMServerInfo": "GLM Information",
  "lbGRMServerInfo": "GRM Information",
  "lbAgentPollingTime": "Agent Polling Time",
  "msgAgentPollingTime": "Information exchange cycle between cloud client agent and GRM server",
  "lbLoginDuplicatgeEnable": "Duplicate user login settings",
  "lbSelectLoginDuplicatgeEnable": "Allow/Disallow",
  "lbLoginDuplicatgeNotiType": "How to notify when a duplicate login is requested",
  "lbLoginDuplicatgeNotiType0": "None",
  "lbLoginDuplicatgeNotiType1": "Mail",
  "lbLoginDuplicatgeNotiType2": "Notice",
  "lbLoginDuplicatgeNotiType3": "Mail & Notice",
  "selHasInclude": "Include",
  "selHasNoInclude": "Not included",

  "msgLoginDuplicatgeEnable": "Determine if the Gooroom client allows users to log in multiple times.",
  "lbPasswordRule": "User password complexity",
  "msgPasswordRule": "Set the complexity when setting the password of the user.",

  "lbPwMinLength": "Password minimum length",
  "lbPwIncludeNumber": "Include numbers",
  "lbPwIncludeUpper": "Include capitalization",
  "lbPwIncludeLower": "Include lowercase",
  "lbPwIncludeSpecial": "Include special",
  "lbPwDiffBefore": "Number of previous passwords and character differences",
  "lbPwDiffZero": "Not match",
  "lbPwDiffSmall": "Little (more 2ea)",
  "lbPwDiffMany": "Much (more 5ea)",

  // 클라우드서비스 관리
  "lbDeleteCloudService": "Delete cloud service",
  "msgDeleteCloudService": "Are you sure you want to delete the cloud service ('{{gcspId}}')?",
  "lbAddCloudService": "Cloud service registration",
  "msgAddCloudService": "Do you want to register cloud service?",
  "lbEditCloudService": "Edit cloud services",
  "msgEditCloudService": "Are you sure you want to modify the cloud service?",
  "dtAddCloudService": "Cloud service registration",
  "dtViewCloudService": "About cloud services",
  "dtEditCloudService": "Edit cloud services",
  "lbCloudServiceId": "Service ID",
  "msgCloudServiceId": "Please enter the service ID.",
  "msgValidCloudServiceId": "Alphabet, number, '-', '_', '.' Please enter only characters.",
  "lbCloudServiceName": "Service Name",
  "msgCloudServiceName": "Please enter a service name.",
  "lbCloudServiceDesc": "Service description",
  "lbCloudServiceIp": "Accessible IP",
  "lbCloudServiceDomain": "Service domain",
  "lbCreateCertType": "How to generate a certificate",
  "selAutoCreateCert": "Auto generation",
  "msgAutoCreateCert": "The server automatically generates a certificate.",
  "selCSRCreateCert": "Create CSR",
  "msgCSRCreateCert": "Approve the certificate using CSR information.",
  "lbCSRInfo": "CSR Information",
  "lbCertInfo": "Certificate Information",
  "lbCert": "Certification",
  "lbPrivateKey": "Private key",

  // 관리자 관리 
  "btConnIpMng": "Access IP management",
  "lbDeleteAdminUser": "Delete manager account",
  "msgDeleteAdminUser": "Are you sure you want to delete the manager account ('{{adminId}}')?",
  "lbAddAdminUser": "Register an administrator account",
  "msgAddAdminUser": "Do you want to register an administrator account?",
  "lbEditAdminUser": "Edit manager account",
  "msgEditAdminUser": "Are you sure you want to edit the manager account?",
  "dtAddAdminUser": "Register an administrator account",
  "dtViewAdminUser": "Administrator account information",
  "dtEditAdminUser": "Edit manager account",
  "lbAdminUserId": "Administrator ID",
  "msgAdminUserId": "Please enter the administrator ID.",
  "msgValidAdminUserId": "Please enter only alphanumeric characters.",
  "lbAdminUserName": "Administrator name",
  "msgAdminUserName": "Please enter an administrator name.",
  "lbAdminPassowrd": "Password",
  "msgAdminPassword": "Please enter a password.",
  "lbAdminConnIp": "Administrator accessable ip",
  "msgAdminConnIp": "Please enter IP or domain.",
  "msgValidAdminConnIp": "Alphabet, number, '.' Please enter only characters.",
  "lbSaveAdminConnIp": "Save connectable IP",
  "msgSaveAdminConnIp": "Do you want to save accessibility information?",
  "dtAdminJobHist": "Administrator ({{adminId}}) History",
  "lbClientPart": "ClientMng Role",
  "lbUserPart": "UserMng Role",
  "lbDesktopPart": "DesktopMng Role",
  "lbNoticePart": "Notice Role",
  "msgNeedPartItem": "You need to select at least one of the administrator rights.",
  "lbManagedClientGroup": "Managed Client Group",
  "lbManagedDept": "Managed Dept.",
  "lbManagedTargetCount": "Count",
  "lbConnectableIp": "Connectable Ip",
  "lbIp": "Ip",
  "msgWrongIpString": "The IP information has been approved.",
  "lbHaveIt": "Exist",
  "lbHaveNotIt": "None",
  "lbAdminSpecifiedRole": "Admin Info. - Role",

  // 호스트정보 관리
  "lbHosts": "Hosts",
  "lbAddHosts": "Hosts information registration",
  "msgAddHosts": "Do you want to register Hosts information?",
  "lbEditHosts": "Edit Hosts information",
  "msgEditHosts": "Do you want to edit hosts information?",
  "msgCopyHosts": "Hosts information has been copied.",
  "dtAddHosts": "Hosts rule registration",
  "dtViewHosts": "Hosts Rule Information",
  "dtEditHosts": "Edit Hosts Rule",
  "dtCopyHosts": "Copy Hosts Rule",
  "lbHostsInfo": "About Hosts",
  "lbHostsCategoty": "About HOSTS",
  "msgHostsInfo": "Please enter host information.",
  "lbDeleteHosts": "Delete Hosts information",
  "msgDeleteHosts": "Are you sure you want to delete Hosts info {{objId}}?",
  "msgShowDetailHosts": "If you select Hosts information, details are displayed.",

  // 업데이트서버정보 관리
  "lbUpdateServer": "UpdateServer",
  "lbAddUpdateServer": "Update server information registration",
  "msgAddUpdateServer": "Do you want to register the update server information?",
  "lbEditUpdateServer": "Edit update server information",
  "msgEditUpdateServer": "Do you want to modify the update server information?",
  "lbDeleteUpdateServer": "Delete update server information",
  "msgDeleteUpdateServer": "Are you sure you want to delete update server information ({{objId}})?",
  "msgCopyUpdateServer": "The update server information has been copied.",
  "dtAddUpdateServer": "Update server information registration",
  "dtViewUpdateServer": "About update server information",
  "dtEditUpdateServer": "Edit update server information",
  "dtCopyUpdateServer": "Copy update server information",
  "lbUpdateServerCategoty": "Update server information",
  "lbMainOSInfo": "Main OS information",
  "msgMainOSInfo": "Please enter the main OS information.",
  "lbBasicOSInfo": "Based OS information",
  "msgBasicOSInfo": "Please enter the underlying OS information.",
  "lbGooroomPrefInfo": "gooroom.pref",
  "msgGooroomPrefInfo": "Please enter information for gooroom.pref.",
  "msgShowDetailUpdateServer": "When you select the update server information, the details are displayed.",

  // 브라우저제어정책 관리
  "lbBrowserRule": "BrowserRule",
  "lbDeleteBrowserRule": "Delete browser control rule",
  "msgDeleteBrowserRule": "Are you sure you want to delete the browser control rule {{objId}}?",
  "lbAddBrowserRule": "Registering a browser control rule",
  "msgAddBrowserRule": "Do you want to register the browser control rule?",
  "lbEditBrowserRule": "Modifying browser control policies",
  "msgEditBrowserRule": "Are you sure you want to edit browser control rule?",
  "msgApplyBrowserRuleChild": "The browser control rule has been applied to the suborganization.",
  "msgCopyBrowserRule": "Copied browser control rule.",
  "dtAddBrowserRule": "Browser control rule registration",
  "dtViewBrowserRule": "Browser control rule information",
  "dtEditBrowserRule": "Modify browser control rule",
  "dtInheritBrowserRule": "Browser control rule inheritance",
  "dtCopyBrowserRule": "Copy browser control rule",
  "dtCategoryBrowserRule": "Browser control rule",
  "lbUseWebSocket": "Using Web Socket",
  "lbUseWebWorker": "Using Web Worker",
  "selPermitRule": "allowed",
  "selNoPermitRule": "Not allowed",
  "lbSetupTrustSite": "Trust site settings",
  "lbSetupUntrustSite": "Set up untrusted sites",
  "lbDevToolUseStop": "Controlling the use of Developer Tools (Web Inspector)",
  "selEnableDevTool": "Developer tools available",
  "selDisableDevTool": "Can not use developer tools",
  "lbLimitDownload": "Download Control",
  "selNolimitDownload": "No download limit",
  "selLimitAllDownload": "Restrict all downloads",
  "lbControlPrint": "Printing control",
  "lbControlShowSource": "Control page source view",
  "btUploadTrustSetup": "Registration of trusted site content using file",
  "btUploadUntrustSetup": "Registration of untrusted site content using file",
  "lbConnectableAddress": "Connection address setting",
  "lbWhiteAddressList": "White Address List",
  "lbSetupTrustSiteInfo": "About trusted site settings",
  "lbSetupUntrustSiteInfo": "About untrusted site settings",

  // 매체제어정책 관리
  "lbMediaRule": "MediaRule",
  "lbDeleteMediaRule": "Delete media control rule",
  "msgDeleteMediaRule": "Are you sure you want to delete the media control rule {{objId}}?",
  "lbAddMediaRule": "Media control rule information registration",
  "msgAddMediaRule": "Do you want to register the media control rule information?",
  "lbEditMediaRule": "Modifying Media Control Rule Information",
  "msgEditMediaRule": "Are you sure you want to modify the media control rule information?",
  "msgApplyMediaRuleChild": "The media control rule has been applied to the suborganization.",
  "msgCopyMediaRule": "Copied media control rule.",
  "dtAddMediaRule": "Media Control Rule Registration",
  "dtViewMediaRule": "About media control policies",
  "dtEditMediaRule": "Modifying Media Control Rule",
  "dtInheritMediaRule": "Inheriting Media Control Rule",
  "dtCopyMediaRule": "Copy Media Control Rule",
  "dtCategoryMediaRule": "Media Control Rule",
  "selCdDvdOn": "CD/DVD Authorization",
  "selCdDvdOff": "No CD/DVD",
  "selPrinterOn": "Printer Authorization",
  "selPrinterOff": "Prohibit printer",
  "selCameraOn": "Camera authorization",
  "selCameraOff": "Camera prohibited",
  "selSoundOn": "Allow sound/mic",
  "selSoundOff": "No sound/mic",
  "selMicrophoneOn": "Allow microphone",
  "selMicrophoneOff": "No microphone",
  "selWifiOn": "WLAN authorization",
  "selWifiOff": "Prohibit WLAN",
  "selUsbKeyboardOn": "USB Keyboard Authorization",
  "selUsbKeyboardOff": "Prohibit USB keyboard",
  "selUsbMouseOn": "USB mouse authorization",
  "selUsbMouseOff": "Prohibit USB mouse",
  "selBluetoothOn": "Bluetooth authorization",
  "selBluetoothOff": "No Bluetooth",
  "dtBluetoothMac": "Connectable Bluetooth Mac Address",
  "selUsbMemoryOn": "USB memory permission",
  "selUsbMemoryOff": "Prohibit USB memory",
  "dtUsbMemorySerial": "Connectable USB Serial Information",  
  "dtWifi": "Wireless LAN",
  "dtCdDvd": "CD/DVD",
  "dtPrinter": "Printer",
  "dtSound": "Sound/Mic.",
  "dtMicrophone": "Microphone",
  "dtCamera": "Camera",
  "dtUsbKeyboard": "USB keyboard",
  "dtUsbMouse": "USB mouse",
  "dtUsbMemory": "USB memory",
  "dtUsbSerial": "USB serial information",
  "dtBluetooth": "Bluetooth",
  "lbBluetoothMac": "Bluetooth MAC address",
  
  // 단말보안정책 관리
  "lbSecuRule": "ClientSecuRule",
  "lbDeleteSecuRule": "Delete a client security rule",
  "msgDeleteSecuRule": "Are you sure you want to delete client security rule {{objId}}?",
  "lbAddSecuRule": "Client security rule information registration",
  "msgAddSecuRule": "Do you want to register the client security rule information?",
  "lbEditSecuRule": "Modify client security rule information",
  "msgEditSecuRule": "Are you sure you want to modify client security rule information?",
  "msgApplySecuRuleChild": "The client security rule has been applied to suborganizations.",
  "msgCopySecuRule": "I have copied the client security rule.",
  "dtAddSecuRule": "Registration of client security rule",
  "dtViewSecuRule": "Client security rule information",
  "dtEditSecuRule": "Modify client security rule",
  "dtInheritSecuRule": "Inheriting client security policies",
  "dtCopySecuRule": "Copy client security rule",
  "dtCategorySecuRule": "Client security rule",
  "lbScreenSaverTime": "Screen Saver Setting Time",
  "lbPasswordChangeCycle": "Password Change Cycle (Days)",
  "selPackageEditStopOn": "Package addition / deletion blocking function turned on",
  "selPackageEditStopOff": "Add / Remove Package Blocking function turned off",
  "lbNetworkMove": "Move",
  "lbSetupFirewall": "Firewall settings",
  "selEnableBasicNetwork": "Basic network permissions",
  "selDisableBasicNetwork": "Block basic network",
  "ttAddItem": "Add item",
  "lbDeleteSecuItem": "Delete",
  "msgDeleteSecuItem": "Are you sure you want to delete the selected item ({{selectCnt}})?",
  "dtPackageEditStop": "Package addition / deletion blocking function",
  "selPackageStopOn": "On",
  "selPackageStopOff": "Off",
  "dtBasicNetwork": "Default Network Allowed",
  "msgValidFirewallAddress": "Please enter only alphabet(A~F) or numeric characters.",

  // 소프트웨어정책 관리
  "lbDeleteSWRule": "Delete a software restriction rule",
  "msgDeleteSWRule": "Are you sure you want to delete the software restriction rule {{objId}}?",
  "lbAddSWRule": "Software restriction rule information registration",
  "msgAddSWRule": "Do you want to register software restriction rule information?",
  "lbEditSWRule": "Modify software restriction rule information",
  "msgEditSWRule": "Are you sure you want to modify software restriction rule information?",
  "msgApplySWRuleChild": "The software restriction rule has been applied to suborganizations.",
  "msgCopySWRule": "You have copied the software restriction rule.",
  "dtAddSWRule": "Software restriction rule registration",
  "dtViewSWRule": "About Software Restriction Policies",
  "dtEditSWRule": "Modifying Software Restriction Policies",
  "dtInheritSWRule": "Software restriction rule inheritance",
  "dtCopySWRule": "Copy Software Restriction Policies",
  "dtCategorySWRule": "Software Restriction Policies",
  "msgSelectSWItem": "Select the software you want to disable.",
  "msStopRunRedSW": "Red colored software is prohibited from running.",
  "lbSWRule": "SoftwarePolicy",

  // 관리자 개인 설정
  "lbAdminTitle": "Manager",
  "lbAdminTitleName": "Name",
  "lbAdminTitleId": "ID",
  "lbAdminCycleTime": "Update Cycle",
  "msgAdminCycleTime": "Please enter a refresh cycle.",
  "msgValidAdminNumber": "Please enter only numbers.",
  "msgValidAdminMinimum": "Can not be less than 5.",
  "lbEditAdminSetup": "Edit administrator settings",
  "msgEditAdminSetup": "Are you sure you want to edit administrator settings?",

  // Dashboard
  "dtViewTotalRule": "Rule integration view",
  "lbRepairViolatedClient": "Client Infringement Action",
  "msgRepairViolatedClient": "Do you want to take action on the infringing client ('{{clientId}}')?",
  "lbRepairJob": "Repair Action",
  "msgRepairJob": "An infringing client action has been created.",
  "msgRepairJobFail": "An infringing client action could not be created.",
  "msgShowOnlyClientGroupRule": "This is the Client connected to the local account. Only client rules are displayed.",
  "lbViolatedClientList": "List of infringing devices",

  "menuSf": "Developing..",
  "menuDividedAdminManage": "Administrator Manage",

  "lbParentGroup": "Parent Client Group",
  "msgSelectParentGroup": "Please select a parent client group.",
  "ttChangeMultiGroupRule": "Multiple changes to client group policies",

  "dtInheritClientConf": "Inherit agent settings",
  "msgInheritClientConf": "Are you sure you want to inherit agent settings?",
  "msgApplyClientConfChild": "The agent settings has been applied to the subgroup.",

  "dtInheritHosts": "Inherit hosts information",
  "msgInheritHosts": "Are you sure you want to inherit hosts information?",
  "msgApplyHostsChild": "The hosts information has been applied to the subgroup.",

  "dtInheritUpdateServer": "Inherit update server information",
  "msgInheritUpdateServer": "Are you sure you want to inherit update server information?",
  "msgApplyUpdateServerChild": "The update server information has been applied to the subgroup.",

  "lbAdminActHistory": "Admin Action History"

};
