export default {
    "updateClientInfo": "Update client information",
    "isDupClientId": "Check for duplicate client ID",
    "updateClientCertToRevoke": "Update client certificate to revoke",
    "deleteClientsCertToRevoke": "Delete client certificates to revoke",
    "createResetViolatedClient": "Create reset for violated client",

    "createClientGroup": "Create client group",
    "deleteClientGroup": "Delete client group",
    "deleteClientGroupList": "Delete list of client groups",
    "updateClientGroup": "Update client group",
    "addClientsInGroup": "Add clients to group",
    "removeClientsInGroup": "Remove clients from group",
    "updateClientGroupConfInherit": "Update client group configuration inheritance",
    "updateRuleForGroups": "Update rules for groups",

    "updatePackageInGroup": "Update package in group",
    "deletePackageInClient": "Delete package in client",
    "createPackageAllUpgrade": "Create upgrade for all packages",
    "createMainPackageUpgrade": "Create main package upgrade",
    "updateTotalPackage": "Update total package",
    "createTotalPackageUpgradeForClient": "Create total package upgrade for client",
    "createTotalPackageUpgradeForGroup": "Create total package upgrade for group",
    "updatePackageInClient": "Update package in client",

    "refusePage": "Refuse page",

    "createMgServerConf": "Create management server configuration",
    "createClientConf": "Create client configuration",
    "cloneClientConf": "Clone client configuration",
    "deleteClientConf": "Delete client configuration",
    "updateClientConf": "Update client configuration",
    "createUpdateServerConf": "Create update server configuration",
    "cloneUpdateServerConf": "Clone update server configuration",
    "updateUpdateServerConf": "Update update server configuration",
    "deleteUpdateServerConf": "Delete update server configuration",
    "createHostNameConf": "Create hostname configuration",
    "cloneHostNameConf": "Clone hostname configuration",
    "updateHostNameConf": "Update hostname configuration",
    "deleteHostNameConf": "Delete hostname configuration",
    "createBrowserRuleConf": "Create browser rule configuration",
    "cloneBrowserRule": "Clone browser rule",
    "deleteBrowserRuleConf": "Delete browser rule configuration",
    "updateBrowserRuleConf": "Update browser rule configuration",
    "createMediaRuleConf": "Create media rule configuration",
    "cloneMediaRule": "Clone media rule",
    "deleteMediaRuleConf": "Delete media rule configuration",
    "updateMediaRuleConf": "Update media rule configuration",
    "createSecurityRule": "Create security rule",
    "cloneSecurityRule": "Clone security rule",
    "updateSecurityRule": "Update security rule",
    "deleteSecurityRule": "Delete security rule",
    "createSoftwareFilter": "Create software filter",
    "updateSoftwareFilter": "Update software filter",
    "deleteSoftwareFilter": "Delete software filter",
    "cloneSoftwareFilter": "Clone software filter",
    "createCtrlCenterItem": "Create control center item",
    "updateCtrlCenterItem": "Update control center item",
    "deleteCtrlCenterItem": "Delete control center item",
    "cloneCtrlCenterItem": "Clone control center item",
    "createPolicyKitRule": "Create policy kit rule",
    "updatePolicyKitRule": "Update policy kit rule",
    "deletePolicyKitRule": "Delete policy kit rule",
    "clonePolicyKitRule": "Clone policy kit rule",

    "createDesktopConf": "Create desktop configuration",
    "updateDesktopConf": "Update desktop configuration",
    "deleteDesktopConf": "Delete desktop configuration",
    "cloneDesktopConf": "Clone desktop configuration",

    "createGcspData": "Create GCSP data",
    "updateGcspData": "Update GCSP data",
    "deleteGcspData": "Delete GCSP data",
    "createGcspCert": "Create GCSP certificate",

    "updateDeptInfo": "Update department information",
    "updateRuleForDepts": "Update rules for departments",
    "updateDeptConfInherit": "Update department configuration inheritance",
    "createDeptInfo": "Create department information",
    "deleteDeptData": "Delete department data",
    "deleteDeptList": "Delete list of departments",
    "createDeptDataFromFile": "Create department data from file",
    "createDeptFileFromData": "Create department file from data",
    "createDeptSampleFileFromData": "Create department sample file from data",

    "module/control": "Control GPMS module",

    "updateJobToCancel": "Update job to cancel",

    "deleteUserClientUseHist": "Delete user client usage history",

    "generateRegKeyNumber": "Generate registration key number",
    "createRegKeyData": "Create registration key data",
    "editRegKeyData": "Edit registration key data",
    "deleteRegKeyData": "Delete registration key data",
    "createProfileSet": "Create profile set",
    "createProfileJob": "Create profile job",
    "deleteProfileSetData": "Delete profile set data",
    "editProfileSetData": "Edit profile set data",
    "createClientSoftware": "Create client software",
    "deleteClientSoftware": "Delete client software",
    "editClientSoftware": "Edit client software",

    "createDesktopApp": "Create desktop application",
    "cloneDesktopApp": "Clone desktop application",
    "deleteDesktopApp": "Delete desktop application",
    "updateDesktopApp": "Update desktop application",

    "createIconData": "Create icon data",
    "deleteIconData": "Delete icon data",
    "updateIconData": "Update icon data",
    "createIconGroupData": "Create icon group data",
    "updateIconGroupData": "Update icon group data",
    "deleteIconGroupData": "Delete icon group data",
    "createIconsInGroup": "Create icons in group",
    "deleteIconInGroup": "Delete icon in group",

    "createThemeData": "Create theme data",
    "deleteThemeData": "Delete theme data",
    "updateThemeData": "Update theme data",
    "createWallpaperData": "Create wallpaper data",
    "deleteWallpaperData": "Delete wallpaper data",
    "updateWallpaperData": "Update wallpaper data",

    "createNotice": "Create notice",
    "updateNotice": "Update notice",
    "deleteNotice": "Delete notice",

    "createNoticeInstantNotice": "Create instant notice",
    "createNoticePublish": "Create notice publish",
    "updateNoticePublish": "Update notice publish",
    "createNoticePublishTarget": "Create notice publish target",

    "registerPortableDataList": "Register portable data list",
    "updateData": "Update data",
    "updateApprove": "Update approval",
    "deletePortableDataList": "Delete portable data list",
    "registerPortableData": "Register portable data",

    "createSiteMng": "Create site management",
    "updateSiteMngData": "Update site management data",
    "updateSiteStatusData": "Update site status data",
    "deleteSiteMngData": "Delete site management data",

    "isExistAdminUserId": "Check if admin user ID exists",
    "createAdminUser": "Create admin user",
    "updateAdminUserData": "Update admin user data",
    "updateCurrentAdminUserData": "Update current admin user data",
    "deleteAdminUserData": "Delete admin user data",
    "updateAdminAddress": "Update admin address",
    "updateLoginTrialData": "Update login trial data",

    "isExistUserId": "Check if user ID exists",
    "createUser": "Create user",
    "createUserWithRule": "Create user with rule",
    "updateUserData": "Update user data",
    "updateUserLoginTrialCount": "Update user login trial count",
    "deleteUserData": "Delete user data",
    "createUsersInDept": "Create users in department",
    "deleteUserInDept": "Delete user in department",
    "deleteUsersInDept": "Delete users in department",
    "createUserDataFromFile": "Create user data from file",
    "createUserFileFromData": "Create user file from data",
    "createUserSampleFileFromData": "Create user sample file from data",
    "approvalUserReq": "Approve user request",
    "denyUserReq": "Deny user request",
    "revokeUsbPermissionFromAdmin": "Revoke USB permission from admin",

    "login": "Login",
    "logout":"Logout",

    "otp/authenticate":"OTP Authenticate",
    "otp/login":"OTP Login",

    "health/checkRepoServerUrl":"Check Repository Server Url",
    "health/registerRepoServer":"Register Repository Server",
    "health/deleteRegisterRepoServer":"Delete Repository Server",
    "health/registerDbServer":"Register DB Server",
    "health/checkDbServerUrl":"Check DB Server Url"
}
