export default {
  "gpmsTest": "커뮤니티",
  "adminMenu": "어드민",

  // columns
  "colDate": "날짜",
  "colNumber": "번호",
  "colName": "이름",
  "colConnReqCount": "요청수",
  "colConnSuccess": "접속성공",
  "colConnFail": "접속실패",
  "colConnRequest": "접속시도",

  "colBootViolated": "부팅보안침해",
  "colExeViolated": "실행보안침해",
  "colOSViolated": "OS보안침해",
  "colMediaViolated": "매체보안침해",

  "colRegCount": "등록수",
  "colRevokeCount": "폐기수",

  "colClientId": "단말아이디",
  "colClientName": "단말이름",
  "colClientGroup": "단말그룹",
  "colGroupName": "그룹이름",
  "colClientCount": "단말수",
  "colUser": "사용자",
  "colUserId": "사용자아이디",
  "colLogType": "로그타입",
  "colLogInfo": "로그정보",
  "colRegDate": "등록일",
  "colModDate": "수정일",
  "colStatus": "상태",
  "colEdit": "수정",
  "colEditDelete": "수정/삭제",

  "colId": "아이디",
  "colLastLoginDate": "최종접속일",
  "colLastLoginIp": "최종접속IP",
  "colLoginId": "접속자",
  "colUseRate": "사용률",

  "colClientRegKey": "단말등록키",
  "colKeyValidDate": "유효날짜",
  "colCertExpireDate": "인증서만료날짜",

  "colRefClientId": "Ref단말아이디",
  "colProfile": "프로파일",
  "colPackageInfo": "패키지정보",
  "colPackageName": "패키지이름",

  "colArchitecture": "아키텍쳐",
  "colVersion": "버전",
  "colInstalledVersion": "설치버전",
  "colAvailVersion": "업데이트가능버전",

  // options
  "optDate": "날짜",
  "searchStartDate": "조회시작일",
  "searchEndDate": "조회종료일",
  "optDivision": "구분",
  "optViolatedDivision": "침해구분",

  "optClientStatus": "단말상태",
  "optKeyword": "검색어",

  // Buttons
  "btnSearch": "조회",
  "btnRegist": "등록",
  "btnSave": "저장",
  "btnClose": "닫기",
  "btnCreate": "생성",

  // Menus
  "menuDashboard": "Dashboard",
  "menuStatistic": "통계",
  "menuDailyViolated": "일별침해통계",
  "menuDailyConnected": "일별접속통계",
  "menuDailyRegistered": "단말등록통계",
  "menuSecurityLog": "보안로그",

  "menuClient": "단말",
  "menuClientManage": "단말관리",
  "menuClientRegKey": "단말등록키",
  "menuClientRule": "단말정책",
  "menuClientSetup": "단말설정",
  "menuClientHosts": "HOSTS",
  "menuClientUpdateServer": "업데이트서버",

  "menuSoftware": "소프트웨어",
  "menuPackageManage": "패키지관리",
  "menuProfileManage": "프로파일정보",

  "menuUser": "사용자",
  "menuUserManage": "사용자관리",

  "menuUseRule": "단말사용정책",
  "menuMediaRuleManage": "매체제어정책",
  "menuBrowserRuleManage": "브라우저제어정책",
  "menuSecurityRuleManage": "단말보안정책",
  "menuSoftwareRuleManage": "소프트웨어제한정책",
  
  "menuDesktop": "데스크톱",
  "menuDesktopManage": "데스크톱정보",
  "menuDesktopAppManage": "데스크톱앱관리",
  "menuCloudServiceManage": "클라우드서비스연동",
  "menuThemeManage": "테마관리",

  "menuJob": "작업",
  "menuJobManage": "작업정보",

  // 공통
  "selOffline": "오프라인",
  "selOnline": "온라인",
  "selViolated": "침해",
  "selUnviolated": "미침해",
  "lbDesc": "설명",
  "lbClientId": "단말아이디",
  "dtSystemError": "시스템오류",

  // 일별접속통계
  "connectRequestCount": "접속요청수",
  "connReqUserCount": "접속요청 사용자수",
  "connReqClientCount": "접속요청 단말수",
  "connSuccessCount": "접속성공",
  "connFailCount": "접속실패",

  // 단말등록통계
  "regClientCount": "등록단말수",
  "revokeClientCount": "폐기단말수",

  // 단말관리
  "ttAddNewGroup": "신규 단말그룹 등록",
  "ttDeleteGroup": "단말그룹 삭제",
  "ttAddClientInGroup": "그룹에 단말추가",
  "ttDeleteClientFromGroup": "그룹에 단말삭제",
  "ttRevokeClient": "단말 폐기",

  "spClientGroup": "단말그룹",
  "spClientDesc": "단말설명",
  "spClientGroupName": "단말그룹이름",
  "spClientGroupDesc": "단말그룹설명",
  "spIsOnline": "온라인여부",
  "spHomeSizeRate": "홈폴더 사용률",
  "spInstalledPkgCnt": "설치패키지수",
  "spBootViolated": "부팅보안침해",
  "spExeViolated": "실행보안침해",
  "spMediaViolated": "매체보안침해",
  "spOSViolated": "OS보안침해",
  "spClientRegDate": "단말 등록일",
  "msgRevokedClient": "폐기된 단말입니다.",

  "dtDeleteClient": "단말 삭제",
  "msgDeleteClient": "단말({{clientCnt}}개)을 삭제하시겠습니까?",

  "dtAddGroup": "단말그룹 등록",
  "dtEditGroup": "단말그룹 수정",
  "dtDeleteGroup": "단말그룹 삭제",
  "msgDeleteGroup": "단말그룹({{groupCnt}}개)을 삭제하시겠습니까?",
  "dtViewGroup": "단말그룹 정보",
  "dtAddClientInGroup": "그룹에 단말 추가",
  "msgAddClientInGroup": "선택한 단말({{clientCnt}}개)을 단말그룹('{{groupName}}')으로 변경하시겠습니까?"
  "dtDeleteClientFromGroup": "그룹에서 단말 삭제",

  "msgAddGroup": "단말그룹을 등록하시겠습니까?",
  "msgEditGroup": "단말그룹을 수정하시겠습니까?",
  "msgDeleteGroup": "단말그룹을 삭제하시겠습니까?",
  "msgInputGroupName": "단말그룹이름을 입력하세요.",
  "msgSelectClient": "단말을 선택하세요.",
  "msgCfmDeleteClientFromGroup": "선택하신 단말을 그룹에서 삭제하시겠습니까?",
  "msgCfmSelectGroupForInsertClient": "단말을 추가할 그룹을 선택하세요.",

  // 단말 등록키 관리
  "dtAddClientKey": "단말 등록키 등록",
  "msgAddClientKey": "단말등록키를 등록하시겠습니까?",
  "dtEditClientKey": "단말 등록키 수정",
  "msgEditClientKey": "단말등록키를 수정하시겠습니까?",
  "dtDeleteClientKey": "단말 등록키 삭제",
  "msgDeleteClientKey": "단말등록키 ('{{regKeyNo}}')을 삭제하시겠습니까?",
  "dtViewClientKey": "단말 등록키 정보",
  "dtCopy": "복사",
  "msgCopyedIntoClipboard": "단말등록키가 클립보드에 복사되었습니다. 붙여넣기 하실 수 있습니다.",
  "spClientRegKey": "등록키",
  "msgCreateClientRegKey": "단말 등록키를 생성하세요.",
  "btnCreateClientRegKey": "키생성",
  "btnCopyToClipboard": "복사하기",
  "colKeyValidDate": "유효날짜",
  "colCertExpireDate": "인증서만료날짜",
  "lbKeyValidDate": "유효날짜",
  "lbCertExpireDate": "인증서만료날짜",
  "lbValidRegIp": "유효 IP 범위",
  "msgInputValidIp": "유효 아이피를 입력하세요.",
  "msgHelpInputIp": "여러개인 경우 콤마(.) 로 구분, 또는 "-" 로 영역 설정 가능합니다.",
  "msgSampleIputIp": "(샘플) '127.0.0.1, 169.0.0.1' 또는 '127.0.0.1 - 127.0.0.10'",

  // 프로파일정보
  "dtExecuteClientProfile": "단말프로파일 실행",
  "msgExecuteClientProfile": "단말프로파일을 실행하시겠습니까?",
  "dtAddClientProfile": "단말프로파일 등록",
  "msgAddClientProfile": "단말프로파일을 등록하시겠습니까?",
  "dtEditClientProfile": "단말프로파일 수정",
  "msgEditClientProfile": "단말프로파일을 수정하시겠습니까?",
  "dtDeleteClientProfile": "단말프로파일 삭제",
  "msgDeleteClientProfile": "단말프로파일 ('{{profileNo}}')를 삭제하시겠습니까?",
  "dtViewClientProfile": "단말프로파일 정보",
  "lbProfileName": "프로파일 이름",
  "msgInputProfileName": "프로파일 이름을 입력하세요.",
  "lbProfileDesc": "프로파일 설명",
  "lbProfileEtcHandle": "기타 패키지 처리방식",
  "selDelete": "삭제함",
  "selNoDelete": "삭제안함",
  "lbReferenceClient": "레퍼런스 단말",
  "msgSelectRefClient": "레퍼런스 단말을 선택하세요.",
  "msgSelectClientInBelow": "아래 목록에서 단말을 선택하세요.",
  "lbTargetClient": "대상 단말",
  "lbPackageInfo": "패키지 정보",
  
  // 패키지관리
  "selShowDiffPackage": "차이있는 패키지만 보기",
  "selShowAllPackage": "전체 패키지 보기",
  "ttPackageUpdate": "패키지 업데이트",
  "ttPackageDelete": "패키지 삭제",
  "dtPackageUpdate": "패키지 업데이트",
  "msgPackageUpdate": "패키지({{packageCnt}}개)를 업데이트하시겠습니까?",
  "dtPackageDelete": "패키지 삭제",
  "msgPackageDelete": "패키지({{packageCnt}}개)를 삭제하시겠습니까?",
  "msgCreatePkgUpdateJob": "패키지 업데이트 작업이 생성되었습니다.",
  "msgNoCreatePkgUpdateJob": "패키지 업데이트 작업이 생성되지 못하였습니다.",
  "msgCreatePkgDeleteJob": "패키지 삭제 작업이 생성되었습니다.",
  "msgNoCreatePkgDeleteJob": "패키지 삭제 작업이 생성되지 못하였습니다.",
  "btnAllUpdate": "전체업데이트",
  "btnAddPackage": "패키지추가",
  "dtInstallSelectedPackage": "선택한 패키지 설치",
  "msgInstallSelectedPackage": "선택한 패키지를 설치하시겠습니까?",
  "dtAllPackageUpadte": "전체패키지 업데이트",
  "msgAllPackageUpadte": "선택하신 단말 또는 그룹에 업데이트 가능 패키지를 모두 업데이트 하겠습니까?",
  "msgSelectClientForUpdate": "패키지를 설치할 단말을 선택하세요.",
  "dtAddClientPackage": "단말패키지 등록",
  "msgAddClientPackage": "단말패키지를 등록하시겠습니까?",
  "dtEditClientPackage": "단말패키지 수정",
  "msgEditClientPackage": "단말패키지를 수정하시겠습니까?",
  "dtViewClientPackage": "단말패키지 정보",
  "lbPackageName": "단말패키지 이름",
  "lbPackageDesc": "단말패키지 설명",

};
