export default {
  "gpmsTest": "커뮤니티",
  "adminMenu": "어드민",

  // columns
  "colDate": "날짜",
  "colNumber": "번호",
  "colName": "이름",
  "colConnReqCount": "요청수",
  "colConnSuccess": "접속성공",
  "colConnFail": "접속실패",
  "colConnRequest": "접속시도",

  "colBootViolated": "부팅보안침해",
  "colExeViolated": "실행보안침해",
  "colOSViolated": "OS보안침해",
  "colMediaViolated": "매체보안침해",

  "colRegCount": "등록수",
  "colRevokeCount": "폐기수",

  "colClientId": "단말아이디",
  "colClientName": "단말이름",
  "colClientGroup": "단말그룹",
  "colGroupName": "그룹이름",
  "colClientCount": "단말수",
  "colUser": "사용자",
  "colUserId": "사용자아이디",
  "colUserNm": "사용자이름",
  "colLogType": "로그타입",
  "colLogInfo": "로그정보",
  "colRegDate": "등록일",
  "colModDate": "수정일",
  "colStatus": "상태",
  "colEdit": "수정",
  "colEditDelete": "수정/삭제",

  "colId": "아이디",
  "colLastLoginDate": "최종접속일",
  "colLastLoginIp": "최종접속IP",
  "colLoginId": "접속자",
  "colUseRate": "사용률",

  "colClientRegKey": "단말등록키",
  "colKeyValidDate": "유효날짜",
  "colCertExpireDate": "인증서만료날짜",

  "colRefClientId": "Ref단말아이디",
  "colProfile": "프로파일",
  "colPackageInfo": "패키지정보",
  "colPackageName": "패키지이름",
  "colPackageUpdate": "패키지업데이트",

  "colArchitecture": "아키텍쳐",
  "colVersion": "버전",
  "colInstalledVersion": "설치버전",
  "colAvailVersion": "업데이트가능버전",

  "colJobNo": "작업번호",
  "colJobName": "작업이름",
  "colJobHistory": "작업이력",
  "colJobStatus": "작업상태",
  "colReqJob": "요청작업",
  "colJobType": "작업타입",
  "colJobProgressStatus": "진행상태",
  "colTargetCnt": "대상단말수",
  "colJobErrorCnt": "작업오류수",
  "colJobCompCnt": "작업완료수",
  "colRegUser": "등록자",
  "colModUser": "수정자",

  "colDivision": "구분",
  "colRuleName": "정책이름",
  "colRuleId": "정책아이디",
  "colInfo": "설명",
  "colDesc": "상세",
  "colThemeName": "테마이름",

  "colDeptNm": "조직",
  "colLoginDate": "최근로그인날짜",
  "colLoginClient": "최종접속단말정보",
  "colViolatedCnt": "침해수",

  // options
  "optDate": "날짜",
  "searchStartDate": "조회시작일",
  "searchEndDate": "조회종료일",
  "optDivision": "구분",
  "optViolatedDivision": "침해구분",

  "optClientStatus": "단말상태",
  "optKeyword": "검색어",

  // Buttons
  "btnSearch": "조회",
  "btnRegist": "등록",
  "btnSave": "저장",
  "btnClose": "닫기",
  "btnCreate": "생성",
  "btnAdd": "추가",
  "btnCopy": "복사",
  "btnSelect": "선택",
  "btnSelectFile": "File선택",

  // Menus
  "menuDashboard": "Dashboard",
  "menuStatistic": "통계",
  "menuDailyViolated": "일별침해통계",
  "menuDailyConnected": "일별접속통계",
  "menuDailyRegistered": "단말등록통계",
  "menuSecurityLog": "보안로그",

  "menuClient": "단말",
  "menuClientManage": "단말관리",
  "menuClientRegKey": "단말등록키",
  "menuClientRule": "단말정책",
  "menuClientSetup": "단말설정",
  "menuClientHosts": "HOSTS",
  "menuClientUpdateServer": "업데이트서버",

  "menuSoftware": "소프트웨어",
  "menuPackageManage": "패키지관리",
  "menuProfileManage": "프로파일정보",

  "menuUser": "사용자",
  "menuUserManage": "사용자관리",

  "menuUseRule": "단말사용정책",
  "menuMediaRuleManage": "매체제어정책",
  "menuBrowserRuleManage": "브라우저제어정책",
  "menuSecurityRuleManage": "단말보안정책",
  "menuSoftwareRuleManage": "소프트웨어제한정책",
  
  "menuDesktop": "데스크톱",
  "menuDesktopManage": "데스크톱정보",
  "menuDesktopAppManage": "데스크톱앱관리",
  "menuCloudServiceManage": "클라우드서비스연동",
  "menuThemeManage": "테마관리",

  "menuJob": "작업",
  "menuJobManage": "작업정보",

  "menuSiteConfig": "구름관리서버설정",
  "menuAdminUserMng": "관리자관리",

  // 공통
  "selOffline": "오프라인",
  "selOnline": "온라인",
  "selViolated": "침해",
  "selUnviolated": "미침해",
  "lbDesc": "설명",
  "lbName": "이름",
  "lbId": "아이디",
  "lbClientId": "단말아이디",
  "dtSystemError": "시스템오류",
  "dtSystemNotice": "시스템알림",
  "dtEditOK": "수정 완료",
  "selBasic": "기본",
  "selOrdinary": "일반",
  "msgInputName": "이름을 입력하세요.",
  "selDelete": "삭제함",
  "selNoDelete": "삭제안함",
  "msgCopyRule": "이 정책을 복사하여 새로운 정책을 생성 하시겠습니까?",
  "dtCopy": "복사",
  "dtApply": "적용",
  "msgApplyRuleToChild": "이 정책을 하위 조직에 적용 하시겠습니까?",
  "dtNameAndId": "이름(아이디)",
  "selNoSelected": "지정안함",
  "msgShowSpecAsSelectRule": "정책 정보를 선택하면 상세 내용이 표시됩니다.",


  // 일별접속통계
  "connectRequestCount": "접속요청수",
  "connReqUserCount": "접속요청 사용자수",
  "connReqClientCount": "접속요청 단말수",
  "connSuccessCount": "접속성공",
  "connFailCount": "접속실패",

  // 단말등록통계
  "regClientCount": "등록단말수",
  "revokeClientCount": "폐기단말수",

  // 단말관리
  "ttAddNewGroup": "신규 단말그룹 등록",
  "ttDeleteGroup": "단말그룹 삭제",
  "ttAddClientInGroup": "그룹에 단말추가",
  "ttDeleteClientFromGroup": "그룹에 단말삭제",
  "ttRevokeClient": "단말 폐기",

  "spClientGroup": "단말그룹",
  "spClientDesc": "단말설명",
  "spClientGroupName": "단말그룹이름",
  "spClientGroupDesc": "단말그룹설명",
  "spIsOnline": "온라인여부",
  "spHomeSizeRate": "홈폴더 사용률",
  "spInstalledPkgCnt": "설치패키지수",
  "spBootViolated": "부팅보안침해",
  "spExeViolated": "실행보안침해",
  "spMediaViolated": "매체보안침해",
  "spOSViolated": "OS보안침해",
  "spClientRegDate": "단말 등록일",
  "msgRevokedClient": "폐기된 단말입니다.",

  "dtDeleteClient": "단말 삭제",
  "msgDeleteClient": "단말({{clientCnt}}개)을 삭제하시겠습니까?",

  "dtAddGroup": "단말그룹 등록",
  "dtEditGroup": "단말그룹 수정",
  "dtDeleteGroup": "단말그룹 삭제",
  "msgDeleteGroup": "단말그룹({{groupCnt}}개)을 삭제하시겠습니까?",
  "dtViewGroup": "단말그룹 정보",
  "dtAddClientInGroup": "그룹에 단말 추가",
  "msgAddClientInGroup": "선택한 단말({{clientCnt}}개)을 단말그룹('{{groupName}}')으로 변경하시겠습니까?",
  "dtDeleteClientFromGroup": "그룹에서 단말 삭제",

  "msgAddGroup": "단말그룹을 등록하시겠습니까?",
  "msgEditGroup": "단말그룹을 수정하시겠습니까?",
  "msgDeleteGroup": "단말그룹을 삭제하시겠습니까?",
  "msgInputGroupName": "단말그룹이름을 입력하세요.",
  "msgSelectClient": "단말을 선택하세요.",
  "msgCfmDeleteClientFromGroup": "선택하신 단말을 그룹에서 삭제하시겠습니까?",
  "msgCfmSelectGroupForInsertClient": "단말을 추가할 그룹을 선택하세요.",
  
  // 단말 등록키 관리
  "dtAddClientKey": "단말 등록키 등록",
  "msgAddClientKey": "단말등록키를 등록하시겠습니까?",
  "dtEditClientKey": "단말 등록키 수정",
  "msgEditClientKey": "단말등록키를 수정하시겠습니까?",
  "dtDeleteClientKey": "단말 등록키 삭제",
  "msgDeleteClientKey": "단말등록키 ('{{regKeyNo}}')을 삭제하시겠습니까?",
  "dtViewClientKey": "단말 등록키 정보",
  "msgCopyedIntoClipboard": "단말등록키가 클립보드에 복사되었습니다. 붙여넣기 하실 수 있습니다.",
  "spClientRegKey": "등록키",
  "msgCreateClientRegKey": "단말 등록키를 생성하세요.",
  "btnCreateClientRegKey": "키생성",
  "btnCopyToClipboard": "복사하기",
  "colKeyValidDate": "유효날짜",
  "colCertExpireDate": "인증서만료날짜",
  "lbKeyValidDate": "유효날짜",
  "lbCertExpireDate": "인증서만료날짜",
  "lbValidRegIp": "유효 IP 범위",
  "msgInputValidIp": "유효 아이피를 입력하세요.",
  "msgHelpInputIp": "여러개인 경우 콤마(.) 로 구분, 또는 "-" 로 영역 설정 가능합니다.",
  "msgSampleIputIp": "(샘플) '127.0.0.1, 169.0.0.1' 또는 '127.0.0.1 - 127.0.0.10'",

  // 프로파일정보
  "dtExecuteClientProfile": "단말프로파일 실행",
  "msgExecuteClientProfile": "단말프로파일을 실행하시겠습니까?",
  "dtAddClientProfile": "단말프로파일 등록",
  "msgAddClientProfile": "단말프로파일을 등록하시겠습니까?",
  "dtEditClientProfile": "단말프로파일 수정",
  "msgEditClientProfile": "단말프로파일을 수정하시겠습니까?",
  "dtDeleteClientProfile": "단말프로파일 삭제",
  "msgDeleteClientProfile": "단말프로파일 ('{{profileNo}}')를 삭제하시겠습니까?",
  "dtViewClientProfile": "단말프로파일 정보",
  "lbProfileName": "프로파일 이름",
  "msgInputProfileName": "프로파일 이름을 입력하세요.",
  "lbProfileDesc": "프로파일 설명",
  "lbProfileEtcHandle": "기타 패키지 처리방식",
  "lbReferenceClient": "레퍼런스 단말",
  "msgSelectRefClient": "레퍼런스 단말을 선택하세요.",
  "msgSelectClientInBelow": "아래 목록에서 단말을 선택하세요.",
  "lbTargetClient": "대상 단말",
  "lbPackageInfo": "패키지 정보",
  
  // 패키지관리
  "selShowDiffPackage": "차이있는 패키지만 보기",
  "selShowAllPackage": "전체 패키지 보기",
  "ttPackageUpdate": "패키지 업데이트",
  "ttPackageDelete": "패키지 삭제",
  "dtPackageUpdate": "패키지 업데이트",
  "msgPackageUpdate": "패키지({{packageCnt}}개)를 업데이트하시겠습니까?",
  "dtPackageDelete": "패키지 삭제",
  "msgPackageDelete": "패키지({{packageCnt}}개)를 삭제하시겠습니까?",
  "msgCreatePkgUpdateJob": "패키지 업데이트 작업이 생성되었습니다.",
  "msgNoCreatePkgUpdateJob": "패키지 업데이트 작업이 생성되지 못하였습니다.",
  "msgCreatePkgDeleteJob": "패키지 삭제 작업이 생성되었습니다.",
  "msgNoCreatePkgDeleteJob": "패키지 삭제 작업이 생성되지 못하였습니다.",
  "btnAllUpdate": "전체업데이트",
  "btnAddPackage": "패키지추가",
  "dtInstallSelectedPackage": "선택한 패키지 설치",
  "msgInstallSelectedPackage": "선택한 패키지를 설치하시겠습니까?",
  "dtAllPackageUpadte": "전체패키지 업데이트",
  "msgAllPackageUpadte": "선택하신 단말 또는 그룹에 업데이트 가능 패키지를 모두 업데이트 하겠습니까?",
  "msgSelectClientForUpdate": "패키지를 설치할 단말을 선택하세요.",
  "dtAddClientPackage": "단말패키지 등록",
  "msgAddClientPackage": "단말패키지를 등록하시겠습니까?",
  "dtEditClientPackage": "단말패키지 수정",
  "msgEditClientPackage": "단말패키지를 수정하시겠습니까?",
  "dtViewClientPackage": "단말패키지 정보",
  "lbPackageName": "단말패키지 이름",
  "lbPackageDesc": "단말패키지 설명",

  // 작업관리
  "dtJobStatus": "작업상태",
  "msgNoResult": "결과가 없습니다.",
  "dtJobModule": "모듈",
  "dtJobTask": "타스크",
  "dtJobMessage": "메세지",
  "dtJobInfo": "작업정보",
  "dtJobNo": "작업번호",
  "dtJobName": "작업이름",
  "dtJobRegDate": "작업생성일",
  "dtJobTargetResult": "작업대상 결과정보",
  "dtJobResultStatus": "작업상태(결과)",
  "dtJobModuleInfo": "작업모듈 정보",
  "btnCancelJob": "작업취소",
  "dtCancelJob": "작업 취소",
  "msgCancelJob": "작업대상 단말중 '작업전' 상태 단말의 작업을 취소하시겠습니까?",

  // 단말정책설정
  "dtAddClientConf": "단말정책설정 등록",
  "msgAddClientConf": "단말정책설정를 등록하시겠습니까?",
  "dtEditClientConf": "단말정책설정 수정",
  "msgEditClientConf": "단말정책설정를 수정하시겠습니까?",
  "dtCopyClientConf": "단말정책설정 복사",
  "msgCopyClientConf": "단말정책설정를 복사하였습니다.",
  "dtViewClientConf": "단말정책설정 정보",
  "dtOSProtect": "운영체제보호",
  "dtInitHomeFolder": "홈폴더 초기화",
  "dtTrustedBoot": "신뢰부팅",
  "dtExeProtect": "실행파일보호",
  "dtMediaProtect": "매체제어",
  "dtAgent": "에이전트",
  "selStop": "중단",
  "selRun": "구동",
  "selExecute": "실행",
  "lbViolatedLogLebel": "침해 로그레벨(수준)",
  "lbClientLogLevel": "단말 로그보기에 표시되는 로그레벨(수준)",
  "lbServerLogLevel": "서버로 전송하는 로그레벨(수준)",
  "lbDeleteAfterSend": "전송후 삭제여부",
  "lbSaveDateAfterSend": "서버전송후 로그보관일수",
  "msgHelpNoDeleteIfZero": "'0' 으로 설정시 삭제하지 않음",
  "dtClientLogSetup": "단말 로그 (JournalD Log) 설정",
  "lbLogFileMax": "로그파일 최대크기(MB)",
  "msgCreateNewFileIfMax": "최대크기에 도달하면 새로운 파일을 생성",
  "msgMegabateUnit": "단위는 Mega-Byte",
  "lbSavedLogFileCount": "보관할 로그파일 갯수",
  "msgDeleteFileIfOverCount": "갯수가 초과되면 오래된 파일을 삭제",
  "lbMinimumDiskSizeRate": "최소 확보 디스크 공간(%)",
  "msgHelpMinimumDiskSizeRate": "단위는 '%'이며 디폴트는 '10%'",
  "msgHelpDiskSizeData": "저널디의 'SystemKeepFree' 설정값",
  "dtSetupConnectableIp": "접속 가능 아이피 설정",
  "dtPermitAllIp": "전체 아이피 허용",
  "selPermit": "허용함",
  "selNoPermit": "허용안함",
  "dtSetupLogLevel": "로그레벨 설정",
  "dtIsUseDeleteFunc": "삭제기능 사용여부",
  "lbSetupClient": "단말 설정",

  // 데스크톱앱관리
  "dtDeleteDesktopApp": "데스크톱앱 삭제",
  "msgDeleteDesktopApp": "데스크톱앱('{{appId}}') 을 삭제하시겠습니까?",
  "dtAddDesktopApp": "데스크톱앱 등록",
  "msgAddDesktopApp": "데스크톱앱을 등록하시겠습니까?",
  "dtEditDesktopApp": "데스크톱앱 수정",
  "msgEditDesktopApp": "데스크톱앱을 수정하시겠습니까?",
  "msgCopyDesktopApp": "데스크톱앱을 복사하였습니다.",
  "dtViewDesktopApp": "데스크톱앱 정보",
  "dtCopyDesktopApp": "데스크톱앱 복사",
  "lbDesktopAppType": "데스크톱앱 종류",
  "lbMountApp": "마운트앱",
  "lbExecuteCmd": "실행 명령어",
  "lbMountUrl": "마운트 URL",
  "lbMountPoint": "마운트 포인트",
  "lbServiceStatus": "서비스 상태",
  "selSeviceOn": "사용",
  "selSeviceOff": "중지",
  "lbIconDivision": "ICON 구분",
  "lbIconInfo": "ICON 정보",
  "lbUseFavicon": "Favicon 사용",
  "lbUseIconLib": "라이브러리 사용",
  "lbFaviconUrl": "Favicon URL",
  "lbIconType": "ICON 타입",
  "lbIconEditDate": "수정일",
  "msgHelpDeleteApp": "현재 데스크톱 앱 삭제는 '데스크톱앱관리' 메뉴에서만 실행 되도록 설정되어 있습니다.",
  "msgAppList": "앱리스트 (아래 전체앱리스트에서 앱을 추가할 수 있습니다.)",
  "lbAppAllList": "전체 앱 리스트",

  // 데스크톱정보 관리
  "dtDeleteDesktopConf": "데스크톱정보 삭제",
  "msgDeleteDesktopConf": "데스크톱정보('{{confId}}')를 삭제하시겠습니까?",
  "dtAddDesktopConf": "데스크톱정보 등록",
  "msgAddDesktopConf": "데스크톱정보를 등록하시겠습니까?",
  "dtEditDesktopConf": "데스크톱정보 수정",
  "msgEditDesktopConf": "데스크톱정보를 수정하시겠습니까?",
  "msgApplyDesktopConfToChild": "데스크톱정보가 하위 조직에 적용되었습니다.",
  "dtCopyDesktopConf": "데스크톱정보 복사",
  "msgCopyDesktopConf": "데스크톱정보를 복사하였습니다.",
  "dtViewDesktopConf": "데스크톱정보 정보",
  "dtInheritDesktopConf": "데스크톱정보 상속",
  "lbTheme": "테마",
  "lbDesktopConf": "데스크톱정보",
  
  // 사용자관리
  "ttAddNewDept": "신규조직등록",
  "ttDeleteDept": "조직삭제",
  "ttChangMultiDeptRule": "조직정책 일괄변경",
  "ttAddUserInDept": "조직에 사용자 추가",
  "ttDeleteUserInDept": "조직에서 사용자 삭제",
  "ttMoveDept": "부서이동",
  "ttAddUser": "신규사용자 생성",
  "dtAddUser": "사용자 등록",
  "dtViewUser": "사용자 정보",
  "dtEditUser": "사용자 수정",
  "dtAddDept": "조직 등록",
  "dtViewDept": "조직 정보",
  "dtEditDept": "조직 수정",
  "dtSelectDept": "조직 선택",
  "dtChangDeptMultiple": "조직 일괄 변경",
  "lbUserId": "사용자아이디",
  "lbPassword": "Password",
  "lbUserName": "사용자이름",
  "lbDept": "조직",
  "lbParentDept": "상위조직",
  "msgEnterUserName": "사용자이름을 입력하세요.",
  "msgSelectDept": "조직을 선택하세요.",
  "msgEnterUserId": "사용자아이디를 입력하세요.",
  "msgUserIdValid": "알파벳 또는 숫자만 입력하세요.",
  "msgEnterPassword": "password를 입력하세요.",
  "msgSelectParentDept": "상위 조직을 선택 하세요.",
  "msgSelectDeptForAddUser": "사용자를 추가할 조직을 선택하세요.",
  "msgSelectUser": "사용자를 선택하세요.",
  "lbDeleteUser": "사용자 삭제",
  "msgDeleteUser": "선택하신 사용자를 조직에서 삭제하시겠습니까?",
  "lbChangeDeptForUser": "사용자 조직 변경",
  "msgChangeDeptForUser": "선택한 사용자({{userCnt}}명)를 조직('{{deptNm}}')으로 변경하시겠습니까?",
  "lbAddUserInDept": "조직('{{deptNm}}')에 사용자 추가",
  "lbDeleteUserInfo": "사용자정보 삭제",
  "msgDeleteUserInfo": "사용자정보('{{userNm}}')을 삭제하시겠습니까?",
  "lbAddUserInfo": "사용자정보 등록",
  "msgAddUserInfo": "사용자정보를 등록하시겠습니까?",
  "lbEditUserInfo": "사용자정보 수정",
  "msgEditUserInfo": "사용자정보를 수정하시겠습니까?",
  "msgChangeDeptRuleSelected": "선택하신 조직의 정책정보를 수정하시겠습니까?",
  "lbDeptId": "조직아이디",
  "lbDeptName": "조직이름",
  "msgEnterDeptName": "조직이름을 입력하세요.",
  "msgEnterDeptId": "조직아이디를 입력하세요.",
  "msgDeptIdValid": "알파벳,숫자,'-','_','.' 문자만 입력하세요.",
  "lbEditDeptInfo": "조직정보 수정",
  "msgEditDeptInfo": "조직정보를 수정하시겠습니까?",
  "lbEditChildDeptInfo": "하위조직 적용여부",
  "lbAddDeptInfo": "조직정보 등록",
  "msgAddDeptInfo": "조직정보를 등록하시겠습니까?",

  // 테마관리
  "lbDeleteTheme": "테마 삭제",
  "msgDeleteTheme": "테마('{{themeNm}}')를 삭제하시겠습니까?",
  "lbAddTheme": "테마 등록",
  "msgAddTheme": "테마를 등록하시겠습니까?",
  "lbEditTheme": "테마 수정",
  "msgEditTheme": "테마를 수정하시겠습니까?",
  "dtAddTheme": "테마 등록",
  "dtViewTheme": "테마 정보",
  "dtEditTheme": "테마 수정",
  "lbThemeId": "테마아이디",
  "lbThemeName": "테마 이름",
  "msgThemeName": "테마 이름을 입력하세요.",
  "lbThemeDesc": "테마 설명",
  "lbIconSetting": "업무환경(Application) 아이콘 설정",
  
  // 관리서버설정
  "lbSaveServerConfig": "구름관리서버설정 저장",
  "msgSaveServerConfig": "구름관리서버설정을 저장하시겠습니까?",
  "msgEditOkServerConfig": "구름관리서버설정이 저장되었습니다.",
  "msgEditErrorServerConfig": "구름관리서버설정이 저장되지 않았습니다.",
  "lbServerInfo": "서버 정보",
  "lbGPMSServerInfo": "GPMS 정보",
  "lbGLMServerInfo": "GLM 정보",
  "lbGRMServerInfo": "GRM 정보",
  "lbAgentPollingTime": "구름 Agent 폴링 타임",
  "msgAgentPollingTime": "구름단말 Agent 와 GRM 서버간의 정보교환 주기",

  // 클라우드서비스 관리
  "lbDeleteCloudService": "클라우드서비스 삭제",
  "msgDeleteCloudService": "클라우드서비스('{{gcspId}}')를 삭제하시겠습니까?",
  "lbAddCloudService": "클라우드서비스 등록",
  "msgAddCloudService": "클라우드서비스를 등록하시겠습니까?",
  "lbEditCloudService": "클라우드서비스 수정",
  "msgEditCloudService": "클라우드서비스를 수정하시겠습니까?",
  "dtAddCloudService": "클라우드서비스 등록",
  "dtViewCloudService": "클라우드서비스 정보",
  "dtEditCloudService": "클라우드서비스 수정",
  "lbCloudServiceId": "서비스아이디",
  "msgCloudServiceId": "서비스아이디를 입력하세요.",
  "msgValidCloudServiceId": "알파벳,숫자,'-','_','.' 문자만 입력하세요.",
  "lbCloudServiceName": "서비스이름",
  "msgCloudServiceName": "서비스이름을 입력하세요.",
  "lbCloudServiceDesc": "서비스설명",
  "lbCloudServiceIp": "접근가능 IP",
  "lbCloudServiceDomain": "서비스 도메인",
  "lbCreateCertType": "인증서 생성 방법",
  "selAutoCreateCert": "자동 생성",
  "msgAutoCreateCert": "구름서버에서 인증서를 자동으로 생성합니다.",
  "selCSRCreateCert": "CSR 생성",
  "msgCSRCreateCert": "CSR정보를 이용하여 인증서를 승인합니다.",
  "lbCSRInfo": "CSR 정보",
  "lbCertInfo": "인증서 정보",
  "lbCert": "인증서",
  "lbPrivateKey": "개인키",

  // 관리자 관리 
  "btConnIpMng": "접속아이피관리",
  "lbDeleteAdminUser": "관리자계정 삭제",
  "msgDeleteAdminUser": "관리자계정('{{adminId}}')을 삭제하시겠습니까?",
  "lbAddAdminUser": "관리자계정 등록",
  "msgAddAdminUser": "관리자계정을 등록하시겠습니까?",
  "lbEditAdminUser": "관리자계정 수정",
  "msgEditAdminUser": "관리자계정을 수정하시겠습니까?",
  "dtAddAdminUser": "관리자계정 등록",
  "dtViewAdminUser": "관리자계정 정보",
  "dtEditAdminUser": "관리자계정 수정",
  "lbAdminUserId": "관리자아이디",
  "msgAdminUserId": "관리자아이디를 입력하세요.",
  "msgValidAdminUserId": "알파벳 또는 숫자만 입력하세요.",
  "lbAdminUserName": "관리자이름",
  "msgAdminUserName": "관리자이름을 입력하세요.",
  "lbAdminPassowrd": "Password",
  "msgAdminPassword": "password를 입력하세요.",
  "lbAdminConnIp": "관리자 접속 가능 아이피",
  "msgAdminConnIp": "아이피 또는 도메인을 입력하세요.",
  "msgValidAdminConnIp": "알파벳,숫자,'.' 문자만 입력하세요.",
  "lbSaveAdminConnIp": "접속가능 아이피 저장",
  "msgSaveAdminConnIp": "접속가능 아이피 정보를 저장하시겠습니까?",
  "dtAdminJobHist": "관리자({{adminId}}) 작업 이력",

  // 호스트정보 관리
  "lbAddHosts": "Hosts 정보 등록",
  "msgAddHosts": "Hosts 정보를 등록하시겠습니까?",
  "lbEditHosts": "Hosts 정보 수정",
  "msgEditHosts": "Hosts 정보를 수정하시겠습니까?",
  "msgCopyHosts": "Hosts 정보를 복사하였습니다.",
  "dtAddHosts": "Hosts정책 등록",
  "dtViewHosts": "Hosts정책 정보",
  "dtEditHosts": "Hosts정책 수정",
  "dtCopyHosts": "Hosts정책 복사",
  "lbHostsInfo": "Hosts 정보",
  "lbHostsCategoty": "HOSTS 정보",
  "msgHostsInfo": "호스트정보를 입력하세요.",
  "lbDeleteHosts": "Hosts 정보 삭제",
  "msgDeleteHosts": "Hosts 정보({{objId}})를 삭제하시겠습니까?",
  "msgShowDetailHosts": "Hosts 정보를 선택하면 상세 내용이 표시됩니다.",

  // 업데이트서버정보 관리
  "lbAddUpdateServer": "업데이트서버정보 등록",
  "msgAddUpdateServer": "업데이트서버정보를 등록하시겠습니까?",
  "lbEditUpdateServer": "업데이트서버정보 수정",
  "msgEditUpdateServer": "업데이트서버정보를 수정하시겠습니까?",
  "lbDeleteUpdateServer": "업데이트서버정보 삭제",
  "msgDeleteUpdateServer": "업데이트서버정보({{objId}})를 삭제하시겠습니까?",
  "msgCopyUpdateServer": "업데이트서버정보를 복사하였습니다.",
  "dtAddUpdateServer": "업데이트서버정보 등록",
  "dtViewUpdateServer": "업데이트서버정보 정보",
  "dtEditUpdateServer": "업데이트서버정보 수정",
  "dtCopyUpdateServer": "업데이트서버정보 복사",
  "lbUpdateServerCategoty": "업데이트서버 정보",
  "lbMainOSInfo": "주 OS 정보",
  "msgMainOSInfo": "주 OS 정보를 입력하세요.",
  "lbBasicOSInfo": "기반 OS 정보",
  "msgBasicOSInfo": "기반 OS 정보를 입력하세요.",
  "lbGooroomPrefInfo": "gooroom.pref",
  "msgGooroomPrefInfo": "gooroom.pref 정보를 입력하세요.",
  "msgShowDetailUpdateServer": "업데이트서버 정보를 선택하면 상세 내용이 표시됩니다.",

  // 브라우져제어정책 관리
  "lbDeleteBrowserRule": "브라우져제어정책 삭제",
  "msgDeleteBrowserRule": "브라우져제어정책({{objId}})을 삭제하시겠습니까?",
  "lbAddBrowserRule": "브라우저제어정책 등록",
  "msgAddBrowserRule": "브라우저제어정책을 등록하시겠습니까?",
  "lbEditBrowserRule": "브라우저제어정책 수정",
  "msgEditBrowserRule": "브라우저제어정책을 수정하시겠습니까?",
  "msgApplyBrowserRuleChild": "브라우저제어정책이 하위 조직에 적용되었습니다.",
  "msgCopyBrowserRule": "브라우저제어정책을 복사하였습니다.",
  "dtAddBrowserRule": "브라우져제어정책 등록",
  "dtViewBrowserRule": "브라우져제어정책 정보",
  "dtEditBrowserRule": "브라우져제어정책 수정",
  "dtInheritBrowserRule": "브라우져제어정책 상속",
  "dtCopyBrowserRule": "브라우져제어정책 복사",
  "dtCategoryBrowserRule": "브라우져제어 정책",
  "lbUseWebSocket": "Web Socket 사용",
  "lbUseWebWorker": "Web Worker 사용",
  "selPermitRule": "허용",
  "selNoPermitRule": "비허용",
  "lbSetupTrustSite": "신뢰사이트 설정",
  "lbSetupUntrustSite": "비신뢰사이트 설정",
  "lbDevToolUseStop": "개발자도구(웹 인스펙터) 사용통제",
  "selEnableDevTool": "개발자도구 사용가능",
  "selDisableDevTool": "개발자도구 사용불가",
  "lbLimitDownload": "다운로드 통제",
  "selNolimitDownload": "다운로드 제한 없음",
  "selLimitAllDownload": "모든 다운로드 제한",
  "lbControlPrint": "프린팅 통제",
  "lbControlShowSource": "페이지 소스보기 통제",
  "btUploadTrustSetup": "파일을 이용하여 비신뢰사이트 내용 등록",
  "btUploadUntrustSetup": "파일을 이용하여 비신뢰사이트 내용 등록",
  "lbConnectableAddress": "접속가능 주소설정",
  "lbWhiteAddressList": "White Address List",
  "lbSetupTrustSiteInfo": "신뢰사이트 설정정보",
  "lbSetupUntrustSiteInfo": "비신뢰사이트 설정정보",

  // 매체제어정책 관리
  "lbDeleteMediaRule": "매체제어정책 삭제",
  "msgDeleteMediaRule": "매체제어정책({{objId}})을 삭제하시겠습니까?",
  "lbAddMediaRule": "매체제어정책정보 등록",
  "msgAddMediaRule": "매체제어정책정보를 등록하시겠습니까?",
  "lbEditMediaRule": "매체제어정책정보 수정",
  "msgEditMediaRule": "매체제어정책정보를 수정하시겠습니까?",
  "msgApplyMediaRuleChild": "매체제어정책이 하위 조직에 적용되었습니다.",
  "msgCopyMediaRule": "매체제어정책을 복사하였습니다.",
  "dtAddMediaRule": "매체제어정책 등록",
  "dtViewMediaRule": "매체제어정책 정보",
  "dtEditMediaRule": "매체제어정책 수정",
  "dtInheritMediaRule": "매체제어정책 상속",
  "dtCopyMediaRule": "매체제어정책 복사",
  "dtCategoryMediaRule": "매체제어 정책",
  "selCdDvdOn": "CD/DVD 허가",
  "selCdDvdOff": "CD/DVD 금지",
  "selPrinterOn": "프린터 허가",
  "selPrinterOff": "프린터 금지",
  "selCameraOn": "카메라 허가",
  "selCameraOff": "카메라 금지",
  "selSoundOn": "사운드(소리, 마이크) 허가",
  "selSoundOff": "사운드(소리, 마이크) 금지",
  "selWifiOn": "무선랜 허가",
  "selWifiOff": "무선랜 금지",
  "selUsbKeyboardOn": "USB키보드 허가",
  "selUsbKeyboardOff": "USB키보드 금지",
  "selUsbMouseOn": "USB마우스 허가",
  "selUsbMouseOff": "USB마우스 금지",
  "selBluetoothOn": "블루투스 허가",
  "selBluetoothOff": "블루투스 금지",
  "dtBluetoothMac": "연결가능 블루투스 Mac 주소",
  "selUsbMemoryOn": "USB 메모리 허가",
  "selUsbMemoryOff": "USB 메모리 금지",
  "dtUsbMemorySerial": "연결가능 USB 시리얼 정보",  
  "dtWifi": "무선랜",
  "dtCdDvd": "CD/DVD",
  "dtPrinter": "프린터",
  "dtSound": "사운드(소리, 마이크)",
  "dtCamera": "카메라",
  "dtUsbKeyboard": "USB키보드",
  "dtUsbMouse": "USB마우스",
  "dtUsbMemory": "USB메모리",
  "dtUsbSerial": "USB시리얼정보",
  "dtBluetooth": "블루투스",
  "dtBluetoothMac": "블루투스 맥주소",
  
  // 단말보안정책 관리
  "lbDeleteSecuRule": "단말보안정책 삭제",
  "msgDeleteSecuRule": "단말보안정책({{objId}})을 삭제하시겠습니까?",
  "lbAddSecuRule": "단말보안정책정보 등록",
  "msgAddSecuRule": "단말보안정책정보를 등록하시겠습니까?",
  "lbEditSecuRule": "단말보안정책정보 수정",
  "msgEditSecuRule": "단말보안정책정보를 수정하시겠습니까?",
  "msgApplySecuRuleChild": "단말보안정책이 하위 조직에 적용되었습니다.",
  "msgCopySecuRule": "단말보안정책을 복사하였습니다.",
  "dtAddSecuRule": "단말보안정책 등록",
  "dtViewSecuRule": "단말보안정책 정보",
  "dtEditSecuRule": "단말보안정책 수정",
  "dtInheritSecuRule": "단말보안정책 상속",
  "dtCopySecuRule": "단말보안정책 복사",
  "dtCategorySecuRule": "단말보안 정책",
  "lbScreenSaverTime": "화면보호기 설정시간(분)",
  "lbPasswordChangeCycle": "패스워드 변경주기(일)",
  "selPackageEditStopOn": "패키지추가/삭제 차단기능 켜짐",
  "selPackageEditStopOff": "패키지추가/삭제 차단기능 꺼짐",
  "lbNetworkMove": "이동",
  "lbSetupFirewall": "방화벽 설정",
  "selEnableBasicNetwork": "기본네트워크 허가",
  "selDisableBasicNetwork": "기본네트워크 차단",
  "ttAddItem": "항목 추가",
  "lbDeleteSecuItem": "삭제",
  "msgDeleteSecuItem": "선택한 항목({{selectCnt}}개)을 삭제하시겠습니까?",
  "dtPackageEditStop": "패키지추가/삭제 차단기능",
  "selPackageStopOn": "켜짐",
  "selPackageStopOff": "꺼짐",
  "dtBasicNetwork": "기본네트워크허용여부",
  
  // 소프트웨어정책 관리
  "lbDeleteSWRule": "소프트웨어제한정책 삭제",
  "msgDeleteSWRule": "소프트웨어제한정책({{objId}})을 삭제하시겠습니까?",
  "lbAddSWRule": "소프트웨어제한정책정보 등록",
  "msgAddSWRule": "소프트웨어제한정책정보를 등록하시겠습니까?",
  "lbEditSWRule": "소프트웨어제한정책정보 수정",
  "msgEditSWRule": "소프트웨어제한정책정보를 수정하시겠습니까?",
  "msgApplySWRuleChild": "소프트웨어제한정책이 하위 조직에 적용되었습니다.",
  "msgCopySWRule": "소프트웨어제한정책을 복사하였습니다.",
  "dtAddSWRule": "소프트웨어제한정책 등록",
  "dtViewSWRule": "소프트웨어제한정책 정보",
  "dtEditSWRule": "소프트웨어제한정책 수정",
  "dtInheritSWRule": "소프트웨어제한정책 상속",
  "dtCopySWRule": "소프트웨어제한정책 복사",
  "dtCategorySWRule": "소프트웨어제한 정책",
  "msgSelectSWItem": "실행금지로 지정할 소프트웨어를 선택하세요.",
  "msStopRunRedSW": "Red 색상의 소프트웨어는 실행을 금지합니다.",

  // 관리자 개인 설정
  "lbAdminTitle": "관리자",
  "lbAdminTitleName": "이름",
  "lbAdminTitleId": "아이디",
  "lbAdminCycleTime": "갱신주기",
  "msgAdminCycleTime": "갱신주기를 입력하세요.",
  "msgValidAdminNumber": "숫자만 입력하세요.",
  "msgValidAdminMinimum": "5보다 작을수 없습니다.",
  "lbEditAdminSetup": "관리자설정 수정",
  "msgEditAdminSetup": "관리자설정을 수정하시겠습니까?",

  // Dashboard
  "dtViewTotalRule": "정책 통합 조회",
  "lbTotalRule": "정책 통합 조회",
  "dtViewTotalRule": "정책 통합 조회",
  
};
