export default {
  "gpmsTest": "커뮤니티",
  "adminMenu": "어드민",

  // columns
  "colDate": "날짜",
  "colNumber": "번호",
  "colName": "이름",
  "colConnReqCount": "요청수",
  "colConnSuccess": "접속성공",
  "colConnFail": "접속실패",
  "colConnRequest": "접속시도",

  "colBootViolated": "부팅보안침해",
  "colExeViolated": "실행보안침해",
  "colOSViolated": "OS보안침해",
  "colMediaViolated": "매체보안침해",

  "colRegCount": "등록수",
  "colRevokeCount": "폐기수",

  "colClientId": "단말아이디",
  "colClientName": "단말이름",
  "colClientGroup": "단말그룹",
  "colGroupName": "그룹이름",
  "colClientCount": "단말수",
  "colUser": "사용자",
  "colUserId": "사용자아이디",
  "colLogType": "로그타입",
  "colLogInfo": "로그정보",
  "colRegDate": "등록일",
  "colModDate": "수정일",
  "colStatus": "상태",
  "colEdit": "수정",
  "colEditDelete": "수정/삭제",

  "colId": "아이디",
  "colLastLoginDate": "최종접속일",
  "colLastLoginIp": "최종접속IP",
  "colLoginId": "접속자",
  "colUseRate": "사용률",

  "colClientRegKey": "단말등록키",
  "colKeyValidDate": "유효날짜",
  "colCertExpireDate": "인증서만료날짜",

  "colRefClientId": "Ref단말아이디",
  "colProfile": "프로파일",
  "colPackageInfo": "패키지정보",
  "colPackageName": "패키지이름",

  "colArchitecture": "아키텍쳐",
  "colVersion": "버전",
  "colInstalledVersion": "설치버전",
  "colAvailVersion": "업데이트가능버전",

  "colJobNo": "작업번호",
  "colJobName": "작업이름",
  "colJobStatus": "작업상태",
  "colJobProgressStatus": "진행상태",
  "colTargetCnt": "대상단말수",
  "colJobErrorCnt": "작업오류수",
  "colJobCompCnt": "작업완료수",
  "colRegUser": "등록자",
  "colModUser": "수정자",

  "colDivision": "구분",
  "colRuleName": "정책이름",
  "colRuleId": "정책아이디",
  "colDesc": "설명",
  "colThemeName": "테마이름",

  // options
  "optDate": "날짜",
  "searchStartDate": "조회시작일",
  "searchEndDate": "조회종료일",
  "optDivision": "구분",
  "optViolatedDivision": "침해구분",

  "optClientStatus": "단말상태",
  "optKeyword": "검색어",

  // Buttons
  "btnSearch": "조회",
  "btnRegist": "등록",
  "btnSave": "저장",
  "btnClose": "닫기",
  "btnCreate": "생성",
  "btnAdd": "추가",
  "btnCopy": "복사",

  // Menus
  "menuDashboard": "Dashboard",
  "menuStatistic": "통계",
  "menuDailyViolated": "일별침해통계",
  "menuDailyConnected": "일별접속통계",
  "menuDailyRegistered": "단말등록통계",
  "menuSecurityLog": "보안로그",

  "menuClient": "단말",
  "menuClientManage": "단말관리",
  "menuClientRegKey": "단말등록키",
  "menuClientRule": "단말정책",
  "menuClientSetup": "단말설정",
  "menuClientHosts": "HOSTS",
  "menuClientUpdateServer": "업데이트서버",

  "menuSoftware": "소프트웨어",
  "menuPackageManage": "패키지관리",
  "menuProfileManage": "프로파일정보",

  "menuUser": "사용자",
  "menuUserManage": "사용자관리",

  "menuUseRule": "단말사용정책",
  "menuMediaRuleManage": "매체제어정책",
  "menuBrowserRuleManage": "브라우저제어정책",
  "menuSecurityRuleManage": "단말보안정책",
  "menuSoftwareRuleManage": "소프트웨어제한정책",
  
  "menuDesktop": "데스크톱",
  "menuDesktopManage": "데스크톱정보",
  "menuDesktopAppManage": "데스크톱앱관리",
  "menuCloudServiceManage": "클라우드서비스연동",
  "menuThemeManage": "테마관리",

  "menuJob": "작업",
  "menuJobManage": "작업정보",

  // 공통
  "selOffline": "오프라인",
  "selOnline": "온라인",
  "selViolated": "침해",
  "selUnviolated": "미침해",
  "lbDesc": "설명",
  "lbName": "이름",
  "lbId": "아이디",
  "lbClientId": "단말아이디",
  "dtSystemError": "시스템오류",
  "dtSystemNotice": "시스템알림",
  "selBasic": "기본",
  "selOrdinary": "일반",
  "msgInputName": "이름을 입력하세요.",
  "selDelete": "삭제함",
  "selNoDelete": "삭제안함",
  "msgCopyRule": "이 정책을 복사하여 새로운 정책을 생성 하시겠습니까?",
  "dtCopy": "복사",
  "dtApply": "적용",
  "msgApplyRuleToChild": "이 정책을 하위 조직에 적용 하시겠습니까?",
  "dtNameAndId": "이름(아이디)",
  "selNoSelected": "지정안함",
  "msgShowSpecAsSelectRule": "정책 정보를 선택하면 상세 내용이 표시됩니다.",


  // 일별접속통계
  "connectRequestCount": "접속요청수",
  "connReqUserCount": "접속요청 사용자수",
  "connReqClientCount": "접속요청 단말수",
  "connSuccessCount": "접속성공",
  "connFailCount": "접속실패",

  // 단말등록통계
  "regClientCount": "등록단말수",
  "revokeClientCount": "폐기단말수",

  // 단말관리
  "ttAddNewGroup": "신규 단말그룹 등록",
  "ttDeleteGroup": "단말그룹 삭제",
  "ttAddClientInGroup": "그룹에 단말추가",
  "ttDeleteClientFromGroup": "그룹에 단말삭제",
  "ttRevokeClient": "단말 폐기",

  "spClientGroup": "단말그룹",
  "spClientDesc": "단말설명",
  "spClientGroupName": "단말그룹이름",
  "spClientGroupDesc": "단말그룹설명",
  "spIsOnline": "온라인여부",
  "spHomeSizeRate": "홈폴더 사용률",
  "spInstalledPkgCnt": "설치패키지수",
  "spBootViolated": "부팅보안침해",
  "spExeViolated": "실행보안침해",
  "spMediaViolated": "매체보안침해",
  "spOSViolated": "OS보안침해",
  "spClientRegDate": "단말 등록일",
  "msgRevokedClient": "폐기된 단말입니다.",

  "dtDeleteClient": "단말 삭제",
  "msgDeleteClient": "단말({{clientCnt}}개)을 삭제하시겠습니까?",

  "dtAddGroup": "단말그룹 등록",
  "dtEditGroup": "단말그룹 수정",
  "dtDeleteGroup": "단말그룹 삭제",
  "msgDeleteGroup": "단말그룹({{groupCnt}}개)을 삭제하시겠습니까?",
  "dtViewGroup": "단말그룹 정보",
  "dtAddClientInGroup": "그룹에 단말 추가",
  "msgAddClientInGroup": "선택한 단말({{clientCnt}}개)을 단말그룹('{{groupName}}')으로 변경하시겠습니까?",
  "dtDeleteClientFromGroup": "그룹에서 단말 삭제",

  "msgAddGroup": "단말그룹을 등록하시겠습니까?",
  "msgEditGroup": "단말그룹을 수정하시겠습니까?",
  "msgDeleteGroup": "단말그룹을 삭제하시겠습니까?",
  "msgInputGroupName": "단말그룹이름을 입력하세요.",
  "msgSelectClient": "단말을 선택하세요.",
  "msgCfmDeleteClientFromGroup": "선택하신 단말을 그룹에서 삭제하시겠습니까?",
  "msgCfmSelectGroupForInsertClient": "단말을 추가할 그룹을 선택하세요.",
  
  // 단말 등록키 관리
  "dtAddClientKey": "단말 등록키 등록",
  "msgAddClientKey": "단말등록키를 등록하시겠습니까?",
  "dtEditClientKey": "단말 등록키 수정",
  "msgEditClientKey": "단말등록키를 수정하시겠습니까?",
  "dtDeleteClientKey": "단말 등록키 삭제",
  "msgDeleteClientKey": "단말등록키 ('{{regKeyNo}}')을 삭제하시겠습니까?",
  "dtViewClientKey": "단말 등록키 정보",
  "msgCopyedIntoClipboard": "단말등록키가 클립보드에 복사되었습니다. 붙여넣기 하실 수 있습니다.",
  "spClientRegKey": "등록키",
  "msgCreateClientRegKey": "단말 등록키를 생성하세요.",
  "btnCreateClientRegKey": "키생성",
  "btnCopyToClipboard": "복사하기",
  "colKeyValidDate": "유효날짜",
  "colCertExpireDate": "인증서만료날짜",
  "lbKeyValidDate": "유효날짜",
  "lbCertExpireDate": "인증서만료날짜",
  "lbValidRegIp": "유효 IP 범위",
  "msgInputValidIp": "유효 아이피를 입력하세요.",
  "msgHelpInputIp": "여러개인 경우 콤마(.) 로 구분, 또는 "-" 로 영역 설정 가능합니다.",
  "msgSampleIputIp": "(샘플) '127.0.0.1, 169.0.0.1' 또는 '127.0.0.1 - 127.0.0.10'",

  // 프로파일정보
  "dtExecuteClientProfile": "단말프로파일 실행",
  "msgExecuteClientProfile": "단말프로파일을 실행하시겠습니까?",
  "dtAddClientProfile": "단말프로파일 등록",
  "msgAddClientProfile": "단말프로파일을 등록하시겠습니까?",
  "dtEditClientProfile": "단말프로파일 수정",
  "msgEditClientProfile": "단말프로파일을 수정하시겠습니까?",
  "dtDeleteClientProfile": "단말프로파일 삭제",
  "msgDeleteClientProfile": "단말프로파일 ('{{profileNo}}')를 삭제하시겠습니까?",
  "dtViewClientProfile": "단말프로파일 정보",
  "lbProfileName": "프로파일 이름",
  "msgInputProfileName": "프로파일 이름을 입력하세요.",
  "lbProfileDesc": "프로파일 설명",
  "lbProfileEtcHandle": "기타 패키지 처리방식",
  "lbReferenceClient": "레퍼런스 단말",
  "msgSelectRefClient": "레퍼런스 단말을 선택하세요.",
  "msgSelectClientInBelow": "아래 목록에서 단말을 선택하세요.",
  "lbTargetClient": "대상 단말",
  "lbPackageInfo": "패키지 정보",
  
  // 패키지관리
  "selShowDiffPackage": "차이있는 패키지만 보기",
  "selShowAllPackage": "전체 패키지 보기",
  "ttPackageUpdate": "패키지 업데이트",
  "ttPackageDelete": "패키지 삭제",
  "dtPackageUpdate": "패키지 업데이트",
  "msgPackageUpdate": "패키지({{packageCnt}}개)를 업데이트하시겠습니까?",
  "dtPackageDelete": "패키지 삭제",
  "msgPackageDelete": "패키지({{packageCnt}}개)를 삭제하시겠습니까?",
  "msgCreatePkgUpdateJob": "패키지 업데이트 작업이 생성되었습니다.",
  "msgNoCreatePkgUpdateJob": "패키지 업데이트 작업이 생성되지 못하였습니다.",
  "msgCreatePkgDeleteJob": "패키지 삭제 작업이 생성되었습니다.",
  "msgNoCreatePkgDeleteJob": "패키지 삭제 작업이 생성되지 못하였습니다.",
  "btnAllUpdate": "전체업데이트",
  "btnAddPackage": "패키지추가",
  "dtInstallSelectedPackage": "선택한 패키지 설치",
  "msgInstallSelectedPackage": "선택한 패키지를 설치하시겠습니까?",
  "dtAllPackageUpadte": "전체패키지 업데이트",
  "msgAllPackageUpadte": "선택하신 단말 또는 그룹에 업데이트 가능 패키지를 모두 업데이트 하겠습니까?",
  "msgSelectClientForUpdate": "패키지를 설치할 단말을 선택하세요.",
  "dtAddClientPackage": "단말패키지 등록",
  "msgAddClientPackage": "단말패키지를 등록하시겠습니까?",
  "dtEditClientPackage": "단말패키지 수정",
  "msgEditClientPackage": "단말패키지를 수정하시겠습니까?",
  "dtViewClientPackage": "단말패키지 정보",
  "lbPackageName": "단말패키지 이름",
  "lbPackageDesc": "단말패키지 설명",

  // 작업관리
  "dtJobStatus": "작업상태",
  "msgNoResult": "결과가 없습니다.",
  "dtJobModule": "모듈",
  "dtJobTask": "타스크",
  "dtJobMessage": "메세지",
  "dtJobInfo": "작업정보",
  "dtJobNo": "작업번호",
  "dtJobName": "작업이름",
  "dtJobRegDate": "작업생성일",
  "dtJobTargetResult": "작업대상 결과정보",
  "dtJobResultStatus": "작업상태(결과)",
  "dtJobModuleInfo": "작업모듈 정보",
  "btnCancelJob": "작업취소",
  "dtCancelJob": "작업 취소",
  "msgCancelJob": "작업대상 단말중 '작업전' 상태 단말의 작업을 취소하시겠습니까?",

  // 단말정책설정
  "dtAddClientConf": "단말정책설정 등록",
  "msgAddClientConf": "단말정책설정를 등록하시겠습니까?",
  "dtEditClientConf": "단말정책설정 수정",
  "msgEditClientConf": "단말정책설정를 수정하시겠습니까?",
  "dtCopyClientConf": "단말정책설정 복사",
  "msgCopyClientConf": "단말정책설정를 복사하였습니다.",
  "dtViewClientConf": "단말정책설정 정보",
  "dtOSProtect": "운영체제보호",
  "dtInitHomeFolder": "홈폴더 초기화",
  "dtTrustedBoot": "신뢰부팅",
  "dtExeProtect": "실행파일보호",
  "dtMediaProtect": "매체제어",
  "dtAgent": "에이전트",
  "selStop": "중단",
  "selRun": "구동",
  "selExecute": "실행",
  "lbViolatedLogLebel": "침해 로그레벨(수준)",
  "lbClientLogLevel": "단말 로그보기에 표시되는 로그레벨(수준)",
  "lbServerLogLevel": "서버로 전송하는 로그레벨(수준)",
  "lbDeleteAfterSend": "전송후 삭제여부",
  "lbSaveDateAfterSend": "서버전송후 로그보관일수",
  "msgHelpNoDeleteIfZero": "'0' 으로 설정시 삭제하지 않음",
  "dtClientLogSetup": "단말 로그 (JournalD Log) 설정",
  "lbLogFileMax": "로그파일 최대크기(MB)",
  "msgCreateNewFileIfMax": "최대크기에 도달하면 새로운 파일을 생성",
  "msgMegabateUnit": "단위는 Mega-Byte",
  "lbSavedLogFileCount": "보관할 로그파일 갯수",
  "msgDeleteFileIfOverCount": "갯수가 초과되면 오래된 파일을 삭제",
  "lbMinimumDiskSizeRate": "최소 확보 디스크 공간(%)",
  "msgHelpMinimumDiskSizeRate": "단위는 '%'이며 디폴트는 '10%'",
  "msgHelpDiskSizeData": "저널디의 'SystemKeepFree' 설정값",
  "dtSetupConnectableIp": "접속 가능 아이피 설정",
  "dtPermitAllIp": "전체 아이피 허용",
  "selPermit": "허용함",
  "selNoPermit": "허용안함",
  "dtSetupLogLevel": "로그레벨 설정",
  "dtIsUseDeleteFunc": "삭제기능 사용여부",
  "lbSetupClient": "단말 설정",

  // 데스크톱앱관리
  "dtDeleteDesktopApp": "데스크톱앱 삭제",
  "msgDeleteDesktopApp": "데스크톱앱('{{appId}}') 을 삭제하시겠습니까?",
  "dtAddDesktopApp": "데스크톱앱 등록",
  "msgAddDesktopApp": "데스크톱앱을 등록하시겠습니까?",
  "dtEditDesktopApp": "데스크톱앱 수정",
  "msgEditDesktopApp": "데스크톱앱을 수정하시겠습니까?",
  "msgCopyDesktopApp": "데스크톱앱을 복사하였습니다.",
  "dtViewDesktopApp": "데스크톱앱 정보",
  "dtCopyDesktopApp": "데스크톱앱 복사",
  "lbDesktopAppType": "데스크톱앱 종류",
  "lbMountApp": "마운트앱",
  "lbExecuteCmd": "실행 명령어",
  "lbMountUrl": "마운트 URL",
  "lbMountPoint": "마운트 포인트",
  "lbServiceStatus": "서비스 상태",
  "selSeviceOn": "사용",
  "selSeviceOff": "중지",
  "lbIconDivision": "ICON 구분",
  "lbIconInfo": "ICON 정보",
  "lbUseFavicon": "Favicon 사용",
  "lbUseIconLib": "라이브러리 사용",
  "lbFaviconUrl": "Favicon URL",
  "lbIconType": "ICON 타입",
  "lbIconEditDate": "수정일",
  "msgHelpDeleteApp": "현재 데스크톱 앱 삭제는 '데스크톱앱관리' 메뉴에서만 실행 되도록 설정되어 있습니다.",
  "msgAppList": "앱리스트 (아래 전체앱리스트에서 앱을 추가할 수 있습니다.)",
  "lbAppAllList": "전체 앱 리스트",

  // 데스크톱정보 관리
  "dtDeleteDesktopConf": "데스크톱정보 삭제",
  "msgDeleteDesktopConf": "데스크톱정보('{{confId}}')를 삭제하시겠습니까?",
  "dtAddDesktopConf": "데스크톱정보 등록",
  "msgAddDesktopConf": "데스크톱정보를 등록하시겠습니까?",
  "dtEditDesktopConf": "데스크톱정보 수정",
  "msgEditDesktopConf": "데스크톱정보를 수정하시겠습니까?",
  "msgApplyDesktopConfToChild": "데스크톱정보가 하위 조직에 적용되었습니다.",
  "dtCopyDesktopConf": "데스크톱정보 복사",
  "msgCopyDesktopConf": "데스크톱정보를 복사하였습니다.",
  "dtViewDesktopConf": "데스크톱정보 정보",
  "dtInheritDesktopConf": "데스크톱정보 상속",
  "lbTheme": "테마",
  "lbDesktopConf": "데스크톱정보",
  

  










  
};
