export default {
    "updateClientInfo": "클라이언트 정보 업데이트",
    "isDupClientId": "클라이언트 ID 중복 확인",
    "updateClientCertToRevoke": "취소할 클라이언트 인증서 업데이트",
    "deleteClientsCertToRevoke": "취소할 클라이언트 인증서 삭제",
    "createResetViolatedClient": "위반된 클라이언트 재설정 생성",
    
    "createClientGroup": "클라이언트 그룹 생성",
    "deleteClientGroup": "클라이언트 그룹 삭제",
    "deleteClientGroupList": "클라이언트 그룹 리스트 삭제",
    "updateClientGroup": "클라이언트 그룹 업데이트",
    "addClientsInGroup": "그룹에 클라이언트 추가",
    "removeClientsInGroup": "그룹에서 클라이언트 제거",
    "updateClientGroupConfInherit": "클라이언트 그룹 구성 상속 업데이트",
    "updateRuleForGroups": "그룹을 위한 정책 업데이트",
    
    "updatePackageInGroup": "그룹 내 패키지 업데이트",
    "deletePackageInClient": "클라이언트에서 패키지 삭제",
    "createPackageAllUpgrade": "모든 패키지 업그레이드 생성",
    "createMainPackageUpgrade": "주 패키지 업그레이드 생성",
    "updateTotalPackage": "전체 패키지 업데이트",
    "createTotalPackageUpgradeForClient": "클라이언트를 위한 전체 패키지 업그레이드 생성",
    "createTotalPackageUpgradeForGroup": "그룹을 위한 전체 패키지 업그레이드 생성",
    "updatePackageInClient": "클라이언트 내 패키지 업데이트",
    
    "refusePage": "페이지 거부",
    
    "createMgServerConf": "Mg 서버 구성 생성",
    "createClientConf": "클라이언트 구성 생성",
    "cloneClientConf": "클라이언트 구성 복제",
    "deleteClientConf": "클라이언트 구성 삭제",
    "updateClientConf": "클라이언트 구성 업데이트",
    "createUpdateServerConf": "업데이트 서버 구성 생성",
    "cloneUpdateServerConf": "업데이트 서버 구성 복제",
    "updateUpdateServerConf": "업데이트 서버 구성 업데이트",
    "deleteUpdateServerConf": "업데이트 서버 구성 삭제",
    "createHostNameConf": "호스트 이름 구성 생성",
    "cloneHostNameConf": "호스트 이름 구성 복제",
    "updateHostNameConf": "호스트 이름 구성 업데이트",
    "deleteHostNameConf": "호스트 이름 구성 삭제",
    "createBrowserRuleConf": "브라우저 정책 구성 생성",
    "cloneBrowserRule": "브라우저 정책 복제",
    "deleteBrowserRuleConf": "브라우저 정책 구성 삭제",
    "updateBrowserRuleConf": "브라우저 정책 구성 업데이트",
    "createMediaRuleConf": "미디어 정책 구성 생성",
    "cloneMediaRule": "미디어 정책 복제",
    "deleteMediaRuleConf": "미디어 정책 구성 삭제",
    "updateMediaRuleConf": "미디어 정책 구성 업데이트",
    "createSecurityRule": "보안 정책 생성",
    "cloneSecurityRule": "보안 정책 복제",
    "updateSecurityRule": "보안 정책 업데이트",
    "deleteSecurityRule": "보안 정책 삭제",
    "createSoftwareFilter": "소프트웨어 필터 생성",
    "updateSoftwareFilter": "소프트웨어 필터 업데이트",
    "deleteSoftwareFilter": "소프트웨어 필터 삭제",
    "cloneSoftwareFilter": "소프트웨어 필터 복제",
    "createCtrlCenterItem": "제어 센터 항목 생성",
    "updateCtrlCenterItem": "제어 센터 항목 업데이트",
    "deleteCtrlCenterItem": "제어 센터 항목 삭제",
    "cloneCtrlCenterItem": "제어 센터 항목 복제",
    "createPolicyKitRule": "정책 킷 정책 생성",
    "updatePolicyKitRule": "정책 킷 정책 업데이트",
    "deletePolicyKitRule": "정책 킷 정책 삭제",
    "clonePolicyKitRule": "정책 킷 정책 복제",
    
    "createDesktopConf": "데스크탑 구성 생성",
    "updateDesktopConf": "데스크탑 구성 업데이트",
    "deleteDesktopConf": "데스크탑 구성 삭제",
    "cloneDesktopConf": "데스크탑 구성 복제",
    
    "createGcspData": "Gcsp 데이터 생성",
    "updateGcspData": "Gcsp 데이터 업데이트",
    "deleteGcspData": "Gcsp 데이터 삭제",
    "createGcspCert": "Gcsp 인증서 생성",
    
    "updateDeptInfo": "부서 정보 업데이트",
    "updateRuleForDepts": "부서 정책 업데이트",
    "updateDeptConfInherit": "부서 구성 상속 업데이트",
    "createDeptInfo": "부서 정보 생성",
    "deleteDeptData": "부서 데이터 삭제",
    "deleteDeptList": "부서 리스트 삭제",
    "createDeptDataFromFile": "파일에서 부서 데이터 생성",
    "createDeptFileFromData": "데이터에서 부서 파일 생성",
    "createDeptSampleFileFromData": "데이터에서 부서 샘플 파일 생성",

    "module/control": "모듈 제어",
    
    "updateJobToCancel": "취소할 작업 업데이트",
    
    "deleteUserClientUseHist": "사용자 클라이언트 사용 기록 삭제",
    
    "generateRegKeyNumber": "등록 키 번호 생성",
    "createRegKeyData": "등록 키 데이터 생성",
    "editRegKeyData": "등록 키 데이터 수정",
    "deleteRegKeyData": "등록 키 데이터 삭제",
    "createProfileSet": "프로필 세트 생성",
    "createProfileJob": "프로필 작업 생성",
    "deleteProfileSetData": "프로필 세트 데이터 삭제",
    "editProfileSetData": "프로필 세트 데이터 수정",
    "createClientSoftware": "클라이언트 소프트웨어 생성",
    "deleteClientSoftware": "클라이언트 소프트웨어 삭제",
    "editClientSoftware": "클라이언트 소프트웨어 수정",
    
    "createDesktopApp": "데스크탑 애플리케이션 생성",
    "cloneDesktopApp": "데스크탑 애플리케이션 복제",
    "deleteDesktopApp": "데스크탑 애플리케이션 삭제",
    "updateDesktopApp": "데스크탑 애플리케이션 업데이트",
    
    "createIconData": "아이콘 데이터 생성",
    "deleteIconData": "아이콘 데이터 삭제",
    "updateIconData": "아이콘 데이터 업데이트",
    "createIconGroupData": "아이콘 그룹 데이터 생성",
    "updateIconGroupData": "아이콘 그룹 데이터 업데이트",
    "deleteIconGroupData": "아이콘 그룹 데이터 삭제",
    "createIconsInGroup": "그룹 내 아이콘 생성",
    "deleteIconInGroup": "그룹 내 아이콘 삭제",
    
    "createThemeData": "테마 데이터 생성",
    "deleteThemeData": "테마 데이터 삭제",
    "updateThemeData": "테마 데이터 업데이트",
    "createWallpaperData": "배경화면 데이터 생성",
    "deleteWallpaperData": "배경화면 데이터 삭제",
    "updateWallpaperData": "배경화면 데이터 업데이트",
    
    "createNotice": "공지 생성",
    "updateNotice": "공지 업데이트",
    "deleteNotice": "공지 삭제",
    
    "createNoticeInstantNotice": "즉시 공지 생성",
    
    "createNoticePublish": "공지 발행 생성",
    "updateNoticePublish": "공지 발행 업데이트",
    
    "createNoticePublishTarget": "공지 발행 대상 생성",
    
    "registerPortableDataList": "휴대용 데이터 목록 등록",
    "updateData": "데이터 업데이트",
    "updateApprove": "승인 업데이트",
    "registerPortableData": "휴대용 데이터 등록",
    
    "createSiteMng": "사이트 관리 생성",
    "updateSiteMngData": "사이트 관리 데이터 업데이트",
    "updateSiteStatusData": "사이트 상태 데이터 업데이트",
    "deleteSiteMngData": "사이트 관리 데이터 삭제",
    
    "isExistAdminUserId": "관리자 사용자 ID 존재 확인",
    "createAdminUser": "관리자 사용자 생성",
    "updateAdminUserData": "관리자 사용자 데이터 업데이트",
    "updateCurrentAdminUserData": "현재 관리자 사용자 데이터 업데이트",
    "deleteAdminUserData": "관리자 사용자 데이터 삭제",
    "updateAdminAddress": "관리자 주소 업데이트",
    "updateLoginTrialData": "로그인 시도 데이터 업데이트",
    
    "isExistUserId": "사용자 ID 존재 확인",
    "createUser": "사용자 생성",
    "createUserWithRule": "정책과 함께 사용자 생성",
    "updateUserData": "사용자 데이터 업데이트",
    "updateUserLoginTrialCount": "사용자 로그인 시도 횟수 업데이트",
    "deleteUserData": "사용자 데이터 삭제",
    "createUsersInDept": "부서에 사용자 생성",
    "deleteUserInDept": "부서에서 사용자 삭제",
    "deleteUsersInDept": "부서에서 사용자들 삭제",
    "createUserDataFromFile": "파일에서 사용자 데이터 생성",
    "createUserFileFromData": "데이터에서 사용자 파일 생성",
    "createUserSampleFileFromData": "데이터에서 사용자 샘플 파일 생성",
    "approvalUserReq": "사용자 요청 승인",
    "denyUserReq": "사용자 요청 거부",
    "revokeUsbPermissionFromAdmin": "관리자에 의해 USB 권한 취소",

    "login":'로그인',
    "logout":"로그아웃",

    "otp/authenticate":"OTP 인증",
    "otp/login":"OTP 로그인",
    "otp/generate":"OTP 인증기기 추가",

    "health/checkRepoServerUrl":"레포 서버 URL 검사",
    "health/registerRepoServer":"레포 서버 등록",
    "health/deleteRegisterRepoServer":"레포 서버 삭제",
    "health/registerDbServer":"DB 서버 삭제",
    "health/checkDbServerUrl":"DB 서버 URL 검사"
}
