/* portable */
export const INPUT_STATUS = Object.freeze({
  INIT: 'INIT',
  SUCCESS: 'SUCCESS',
  EMPTY: 'EMPTY',
  FAILURE: 'FAILRE',
  INVALID: 'INVALID',
});

export const PORTABLE_APPROVE_STATUS_TYPE = Object.freeze({
  REQUEST: 'REQUEST',
  REAPPROVE: 'REAPPROVE',
  APPROVE: 'APPROVE',
});

export const PORTABLE_APPROVE = {
  [PORTABLE_APPROVE_STATUS_TYPE.REQUEST]: 'txApproveRequest',
  [PORTABLE_APPROVE_STATUS_TYPE.REAPPROVE]: 'txApproveReApprove',
  [PORTABLE_APPROVE_STATUS_TYPE.APPROVE]: 'txApproveApprove',
};

export const PORTABLE_IMAGE_STATUS_TYPE = Object.freeze({
  APPLY: 'APPLY',
  CREATE: 'CREATE',
  COMPLETE: 'COMPLETE',
  DELETE: 'DELETE',
  FAILED: 'FAILED',
  ABORTED: 'ABORTED',

  APPLY_KR: '신청',
  CREATE_KR: '생성',
  COMPLETE_KR: '경로전송',
  DELETE_KR: '삭제',
  FAILED_KR: '실패',
  ABORTED_KR: '중단',
});

export const PORTABLE_IMAGE_STATUS_CODE = Object.freeze({
  [PORTABLE_IMAGE_STATUS_TYPE.APPLY]: 'APPLY',
  [PORTABLE_IMAGE_STATUS_TYPE.APPLY_KR]: 'APPLY',
  [PORTABLE_IMAGE_STATUS_TYPE.CREATE]: 'CREATE',
  [PORTABLE_IMAGE_STATUS_TYPE.CREATE_KR]: 'CREATE',
  [PORTABLE_IMAGE_STATUS_TYPE.COMPLETE]: 'COMPLETE',
  [PORTABLE_IMAGE_STATUS_TYPE.COMPLETE_KR]: 'COMPLETE',
  [PORTABLE_IMAGE_STATUS_TYPE.DELETE]: 'DELETE',
  [PORTABLE_IMAGE_STATUS_TYPE.DELETE_KR]: 'DELETE',
  [PORTABLE_IMAGE_STATUS_TYPE.FAILED]: 'FAILED',
  [PORTABLE_IMAGE_STATUS_TYPE.FAILED_KR]: 'FAILED',
  [PORTABLE_IMAGE_STATUS_TYPE.ABORTED]: 'ABORTED',
  [PORTABLE_IMAGE_STATUS_TYPE.ABORTED_KR]: 'ABORTED',
});

const PORTABLE_IMAGE_LOCALE = Object.freeze({
  APPLY: 'txPortableImageApply',
  CREATE: 'txPortableImageCreate',
  COMPLETE: 'txPortableImageComplete',
  DELETE: 'txPortableImageDelete',
  FAILED: 'txPortableImageFailed',
  ABORTED: 'txPortableImageAborted',
});

export const PORTABLE_IMAGE_STATUS_TO_LOCALE = {
  [PORTABLE_IMAGE_STATUS_TYPE.APPLY]: PORTABLE_IMAGE_LOCALE.APPLY,
  [PORTABLE_IMAGE_STATUS_TYPE.CREATE]: PORTABLE_IMAGE_LOCALE.CREATE,
  [PORTABLE_IMAGE_STATUS_TYPE.COMPLETE]: PORTABLE_IMAGE_LOCALE.COMPLETE,
  [PORTABLE_IMAGE_STATUS_TYPE.DELETE]: PORTABLE_IMAGE_LOCALE.DELETE,
  [PORTABLE_IMAGE_STATUS_TYPE.FAILED]: PORTABLE_IMAGE_LOCALE.FAILED,
  [PORTABLE_IMAGE_STATUS_TYPE.ABORTED]: PORTABLE_IMAGE_LOCALE.ABORTED,

  [PORTABLE_IMAGE_STATUS_TYPE.APPLY_KR]: PORTABLE_IMAGE_LOCALE.APPLY,
  [PORTABLE_IMAGE_STATUS_TYPE.CREATE_KR]: PORTABLE_IMAGE_LOCALE.CREATE,
  [PORTABLE_IMAGE_STATUS_TYPE.COMPLETE_KR]: PORTABLE_IMAGE_LOCALE.COMPLETE,
  [PORTABLE_IMAGE_STATUS_TYPE.DELETE_KR]: PORTABLE_IMAGE_LOCALE.DELETE,
  [PORTABLE_IMAGE_STATUS_TYPE.FAILED_KR]: PORTABLE_IMAGE_LOCALE.FAILED,
  [PORTABLE_IMAGE_STATUS_TYPE.ABORTED_KR]: PORTABLE_IMAGE_LOCALE.ABORTED,
}

export const PORTABLE_APPLY_SEARCH_TYPE = {
  USER: {
    id: 'USER',
    value: 'chUserId',
    text: 'stUser',
  },
  REGDATE: {
     id: 'REGDT',
    value: 'chRegDate',
    text: 'stRegDate',   
  },
  CREATEDDATE: {
     id: 'CREATEDDT',
    value: 'chCreateDate',
    text: 'stImageCreatedDate',   
  },
  ALL: {
     id: 'ALL',
    value: 'ALL',
    text: 'stAll',   
  },
};