const routes = {
  '/': 'Home',

  '/master': '구름관리서버설정',
  '/master/domain': '도메인관리',
  '/master/admin': '관리자관리',
  '/master/server': '서버정보설정',
  
  '/clients': '단말관리',
  '/clients/clientmanage': '등록관리',
  '/clients/clientgroup': '그룹관리',
  '/clients/packages': '패키지관리',
  '/clients/jobmanage': '작업관리',

  '/clientconfig': '단말설정',
  '/clientconfig/desktop': '데스크톱환경',
  '/clientconfig/update': '업데이트서버설정',
  '/clientconfig/host': 'HOSTS설정',
  '/clientconfig/setting': '단말정책설정',

  '/userconfig': '사용자정책관리',
  '/userconfig/media': '매체제어정책관리',
  '/userconfig/browser': '브라우저제어정책관리',
  '/userconfig/security': '단말보안정책관리',
  
  '/base': 'Base',
  '/base/cards': 'Cards',
  '/base/forms': 'Forms',
  '/base/switches': 'Switches',
  '/base/tables': 'Tables',
  '/base/tabs': 'Tabs',
  '/base/breadcrumbs': 'Breadcrumbs',
  '/base/carousels': 'Carousels',
  '/base/collapses': 'Collapses',
  '/base/jumbotrons': 'Jumbotrons',
  '/base/list-groups': 'List Groups',
  '/base/navbars': 'Navbars',
  '/base/navs': 'Navs',
  '/base/paginations': 'Paginations',
  '/base/popovers': 'Popovers',
  '/base/progress-bar': 'Progress Bar',
  '/base/tooltips': 'Tooltips',
  '/buttons': 'Buttons',
  '/buttons/buttons': 'Buttons',
  '/buttons/social-buttons': 'Social Buttons',
  '/buttons/button-dropdowns': 'Button Dropdowns',
  '/buttons/button-groups': 'Button Groups',
  '/charts': 'Charts',
  '/dashboard': 'Dashboard',
  '/icons': 'Icons',
  '/icons/flags': 'Flags',
  '/icons/font-awesome': 'Font Awesome',
  '/icons/simple-line-icons': 'Simple Line Icons',
  '/notifications': 'Notifications',
  '/notifications/alerts': 'Alerts',
  '/notifications/badges': 'Badges',
  '/notifications/modals': 'Modals',
  '/theme': 'Theme',
  '/theme/colors': 'Colors',
  '/theme/typography': 'Typography',
  '/widgets': 'Widgets'
};
export default routes;
